
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio              TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS messenger_url    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS messenger_public BOOLEAN DEFAULT FALSE;
