

DELETE FROM bible_questions a
USING bible_questions b
WHERE lower(btrim(a.question)) = lower(btrim(b.question))
  AND (a.created_at, a.id) > (b.created_at, b.id);


WITH new_q(category, difficulty, question, options, correct_index, source_ref, explanation) AS (
  VALUES
  ('old_testament','easy','What food fell from heaven to feed Israel in the wilderness?',
   '["Quail only","Manna","Barley bread","Figs"]',1,'Exodus 16:15',
   'Israel called the bread from heaven "manna" and ate it for forty years.'),
  ('old_testament','easy','Which sea did God part so Israel could escape Pharaoh''s army?',
   '["The Sea of Galilee","The Dead Sea","The Red Sea","The Great Sea"]',2,'Exodus 14:21-22',
   'The waters stood like walls and Israel crossed on dry ground.'),
  ('old_testament','easy','What idol did Israel make while Moses was on Mount Sinai?',
   '["A golden calf","A bronze serpent","A silver eagle","A wooden bull"]',0,'Exodus 32:4',
   'Aaron fashioned a golden calf while Moses received the Law.'),
  ('old_testament','easy','What instrument did young David play to soothe King Saul?',
   '["A flute","A trumpet","A tambourine","A harp"]',3,'1 Samuel 16:23',
   'David''s harp drove away the distressing spirit troubling Saul.'),
  ('old_testament','easy','What did Moses'' staff become when he threw it down before Pharaoh?',
   '["A serpent","A torch","A vine","A sword"]',0,'Exodus 7:10',
   'Aaron cast down the rod and it became a serpent before Pharaoh.'),
  ('old_testament','easy','What did God confuse so the Tower of Babel was abandoned?',
   '["The builders'' tools","The builders'' language","The city''s water","The king''s heart"]',1,'Genesis 11:7-9',
   'God confused their language and scattered them over the earth.'),
  ('old_testament','easy','What was put on the doorposts so the final plague would pass over?',
   '["Olive oil","Water from the Nile","The blood of a lamb","Goat''s milk"]',2,'Exodus 12:7-13',
   'The lamb''s blood marked the homes the Lord passed over — the first Passover.'),

  ('old_testament','medium','How many men did God keep with Gideon to defeat Midian?',
   '["3,000","12,000","1,000","300"]',3,'Judges 7:7',
   'God cut the army to 300 so Israel would know the victory was His.'),
  ('old_testament','medium','Which prophetess judged Israel and rode to battle with Barak?',
   '["Deborah","Miriam","Huldah","Anna"]',0,'Judges 4:4-9',
   'Deborah judged under a palm tree and went with Barak against Sisera.'),
  ('old_testament','medium','Whose donkey spoke after seeing the Angel of the Lord?',
   '["Moses''","Balaam''s","Saul''s","Job''s"]',1,'Numbers 22:28',
   'The Lord opened the donkey''s mouth to stop Balaam''s reckless path.'),
  ('old_testament','medium','What did the widow of Zarephath never run out of during the famine?',
   '["Bread and wine","Water and salt","Flour and oil","Milk and honey"]',2,'1 Kings 17:14-16',
   'Her bin of flour and jar of oil never emptied, just as Elijah promised.'),
  ('old_testament','medium','For which king did the sun''s shadow move backward as a sign of healing?',
   '["Hezekiah","Josiah","Uzziah","Ahaz"]',0,'2 Kings 20:9-11',
   'The shadow went back ten degrees as a sign Hezekiah would recover.'),
  ('old_testament','medium','What sin did Achan commit after the fall of Jericho?',
   '["He deserted the army","He kept plunder God had forbidden","He worshiped Baal","He broke the Sabbath"]',1,'Joshua 7:20-21',
   'Achan hid a garment, silver, and gold that were devoted to destruction.'),
  ('old_testament','medium','Who was the left-handed judge who defeated King Eglon of Moab?',
   '["Othniel","Shamgar","Gideon","Ehud"]',3,'Judges 3:15-21',
   'Ehud''s left-handedness let him conceal the blade that freed Israel.'),
  ('old_testament','medium','What did Elisha make float on the Jordan River?',
   '["A bronze coin","An iron axe head","A wooden bowl","A soldier''s shield"]',1,'2 Kings 6:5-7',
   'Elisha threw in a stick and the borrowed iron axe head floated.'),

  ('old_testament','hard','Which king led a great reformation after the Book of the Law was found?',
   '["Joash","Jehoshaphat","Josiah","Jotham"]',2,'2 Kings 22-23',
   'Josiah tore his robes at the reading and purged idolatry from Judah.'),
  ('old_testament','hard','Whose harsh answer caused the kingdom of Israel to split in two?',
   '["Rehoboam''s","Jeroboam''s","Solomon''s","Saul''s"]',0,'1 Kings 12:13-16',
   'Rehoboam rejected the elders'' counsel, and ten tribes broke away.'),
  ('old_testament','hard','Which lame son of Jonathan ate at King David''s table?',
   '["Ish-bosheth","Adonijah","Amasa","Mephibosheth"]',3,'2 Samuel 9:13',
   'David showed Mephibosheth kindness for Jonathan''s sake.'),
  ('old_testament','hard','Which of David''s sons stole the people''s hearts and led a rebellion?',
   '["Amnon","Absalom","Adonijah","Shimei"]',1,'2 Samuel 15:1-6',
   'Absalom won Israel''s hearts at the gate, then rose against his father.'),
  ('old_testament','hard','Which prophet bought a field while Jerusalem was under siege?',
   '["Isaiah","Ezekiel","Amos","Jeremiah"]',3,'Jeremiah 32:9',
   'Buying land in wartime was God''s sign that Israel would return home.'),

  ('new_testament','easy','What tiny seed did Jesus compare the kingdom of heaven to?',
   '["A mustard seed","A wheat grain","A fig seed","A grape seed"]',0,'Matthew 13:31-32',
   'The smallest seed grows into a tree where birds nest — so grows the kingdom.'),
  ('new_testament','easy','In which garden did Jesus pray the night He was arrested?',
   '["Eden","En Gedi","Gethsemane","Bethany"]',2,'Matthew 26:36',
   'In Gethsemane Jesus prayed, "Not as I will, but as You will."'),
  ('new_testament','easy','For how many pieces of silver did Judas agree to betray Jesus?',
   '["Twenty","Thirty","Forty","Fifty"]',1,'Matthew 26:15',
   'Thirty pieces of silver — the price of a slave foretold in Zechariah.'),
  ('new_testament','easy','Which Roman governor washed his hands at Jesus'' trial?',
   '["Pontius Pilate","Herod Antipas","Felix","Festus"]',0,'Matthew 27:24',
   'Pilate washed his hands, claiming innocence of Jesus'' blood.'),
  ('new_testament','easy','Which angel told Mary she would give birth to Jesus?',
   '["Michael","A seraph","An unnamed angel","Gabriel"]',3,'Luke 1:26-31',
   'Gabriel announced that Mary would bear the Son of the Highest.'),
  ('new_testament','easy','Who first heard the news of Jesus'' birth in the fields near Bethlehem?',
   '["The Magi","Shepherds","King Herod","Simeon"]',1,'Luke 2:8-11',
   'An angel brought the good news of great joy to shepherds keeping watch.'),
  ('new_testament','easy','In which parable does a son waste his inheritance and return home?',
   '["The Good Samaritan","The Talents","The Prodigal Son","The Sower"]',2,'Luke 15:11-24',
   'The father ran to meet his returning son — a picture of God''s welcome.'),

  ('new_testament','medium','Who came to Jesus by night and was told "You must be born again"?',
   '["Nicodemus","Joseph of Arimathea","Gamaliel","Caiaphas"]',0,'John 3:1-7',
   'Nicodemus the Pharisee learned that the new birth is by the Spirit.'),
  ('new_testament','medium','Where did Jesus speak with the Samaritan woman?',
   '["At the pool of Bethesda","At the temple gate","By the Sea of Galilee","At Jacob''s well"]',3,'John 4:5-7',
   'At Jacob''s well Jesus offered her living water.'),
  ('new_testament','medium','Which blind man of Jericho cried, "Son of David, have mercy on me"?',
   '["Lazarus","Bartimaeus","Malchus","Barabbas"]',1,'Mark 10:46-47',
   'Blind Bartimaeus threw off his garment and received his sight.'),
  ('new_testament','medium','In the parable of the sower, what does the seed stand for?',
   '["Faith","Money","The word of God","The church"]',2,'Luke 8:11',
   '"The seed is the word of God" — the soils are the hearts that receive it.'),
  ('new_testament','medium','Who was forced to carry Jesus'' cross part of the way?',
   '["Simon of Cyrene","Simon Peter","Joseph of Arimathea","John"]',0,'Matthew 27:32',
   'Simon of Cyrene was compelled to carry the cross behind Jesus.'),
  ('new_testament','medium','On the road to which village did the risen Jesus walk with two disciples?',
   '["Damascus","Jericho","Emmaus","Gaza"]',2,'Luke 24:13-15',
   'Their hearts burned as He opened the Scriptures on the Emmaus road.'),
  ('new_testament','medium','From which mount did Jesus ascend into heaven?',
   '["Mount Sinai","The Mount of Olives","Mount Carmel","Mount Tabor"]',1,'Acts 1:9-12',
   'From the Mount of Olives Jesus was taken up, and there He will return.'),
  ('new_testament','medium','Who became the first Christian martyr while Saul looked on?',
   '["James","Barnabas","Silas","Stephen"]',3,'Acts 7:58-60',
   'Stephen saw heaven opened and prayed for those who stoned him.'),

  ('new_testament','hard','Whose ear did Peter cut off in the garden?',
   '["Malchus, the high priest''s servant","A Roman soldier''s","Judas Iscariot''s","A temple guard captain''s"]',0,'John 18:10',
   'Jesus healed Malchus — His last miracle before the cross.'),
  ('new_testament','hard','Which couple explained the way of God more accurately to Apollos?',
   '["Ananias and Sapphira","Priscilla and Aquila","Philemon and Apphia","Andronicus and Junia"]',1,'Acts 18:26',
   'The tentmakers Priscilla and Aquila discipled the eloquent Apollos.'),
  ('new_testament','hard','In which city did Paul preach about the "unknown god" at the Areopagus?',
   '["Corinth","Ephesus","Rome","Athens"]',3,'Acts 17:22-23',
   'In Athens Paul proclaimed the God the philosophers did not know.'),
  ('new_testament','hard','Who believed and was baptized after an earthquake shook open the prison?',
   '["The Philippian jailer","A Roman centurion","The temple captain","Herod''s steward"]',0,'Acts 16:25-34',
   'The jailer asked, "What must I do to be saved?" — and believed with his house.'),
  ('new_testament','hard','Before which two governors did Paul make his defense in Caesarea?',
   '["Pilate and Herod","Gallio and Sergius","Felix and Festus","Annas and Caiaphas"]',2,'Acts 24-25',
   'Paul testified before Felix, then Festus — and appealed to Caesar.'),

  ('character','easy','Who was Lois?',
   '["Timothy''s grandmother of sincere faith","Lydia''s sister in Philippi","A prophetess in Jerusalem","Priscilla''s mother"]',0,'2 Timothy 1:5',
   'Paul recalled the genuine faith that lived first in grandmother Lois.'),
  ('character','easy','Who was Onesimus?',
   '["A jailer in Philippi","A silversmith in Ephesus","A scribe in Corinth","A runaway slave returned to Philemon"]',3,'Philemon 1:10-16',
   'Paul sent Onesimus back no longer as a slave but as a beloved brother.'),
  ('character','easy','Who watched over baby Moses as he floated in the basket?',
   '["His mother Jochebed","His sister Miriam","Pharaoh''s daughter","A palace servant"]',1,'Exodus 2:4',
   'Miriam stood at a distance and arranged for Moses'' own mother to nurse him.'),
  ('character','easy','Who was Abraham''s nephew who chose to live near Sodom?',
   '["Laban","Ishmael","Lot","Eliezer"]',2,'Genesis 13:10-12',
   'Lot chose the well-watered plain — and pitched his tent toward Sodom.'),
  ('character','easy','Who said he would not believe unless he saw the nail prints in Jesus'' hands?',
   '["Philip","Thomas","Andrew","Matthew"]',1,'John 20:25',
   'A week later Thomas confessed, "My Lord and my God!"'),
  ('character','easy','Who was the priest who raised the boy Samuel at Shiloh?',
   '["Eli","Elkanah","Aaron","Zadok"]',0,'1 Samuel 1-3',
   'Eli taught Samuel to answer, "Speak, Lord, for Your servant hears."'),
  ('character','easy','Which queen said, "If I perish, I perish," before approaching the king?',
   '["Ruth","Abigail","Bathsheba","Esther"]',3,'Esther 4:16',
   'Esther risked death to plead for her people — and the king received her.'),

  ('character','medium','Who was David''s covenant friend, the son of King Saul?',
   '["Joab","Jonathan","Abner","Ittai"]',1,'1 Samuel 18:1-3',
   'Jonathan loved David as his own soul and protected him from Saul.'),
  ('character','medium','Which prophet was fed by ravens at the Brook Cherith?',
   '["Elisha","Jeremiah","Elijah","Amos"]',2,'1 Kings 17:4-6',
   'Ravens brought Elijah bread and meat, morning and evening.'),
  ('character','medium','Which king seized Naboth''s vineyard after a false trial?',
   '["Ahab","Jeroboam","Omri","Jehu"]',0,'1 Kings 21:1-16',
   'Jezebel arranged false witnesses so Ahab could take the vineyard.'),
  ('character','medium','Who was the silversmith who stirred up a riot in Ephesus?',
   '["Alexander","Tertullus","Tychicus","Demetrius"]',3,'Acts 19:24-29',
   'Demetrius made shrines of Artemis and feared the gospel''s effect on trade.'),
  ('character','medium','Who was Naomi''s daughter-in-law who turned back to Moab?',
   '["Orpah","Ruth","Tamar","Dinah"]',0,'Ruth 1:14-15',
   'Orpah kissed Naomi goodbye, but Ruth clung to her.'),
  ('character','medium','Whose wise appeal stopped David from taking revenge on Nabal?',
   '["Michal''s","Bathsheba''s","Abigail''s","Tamar''s"]',2,'1 Samuel 25:23-35',
   'Abigail''s humility turned David from bloodshed; she later became his wife.'),
  ('character','medium','Who advised Moses to appoint judges over thousands and hundreds?',
   '["Aaron","Jethro","Hur","Joshua"]',1,'Exodus 18:17-22',
   'Moses'' father-in-law Jethro saw the burden and proposed shared leadership.'),
  ('character','medium','Who "walked with God" and was taken so that he did not see death?',
   '["Methuselah","Lamech","Noah","Enoch"]',3,'Genesis 5:24',
   '"Enoch walked with God; and he was not, for God took him."'),

  ('character','hard','Who read the Book of the Law aloud to the returned exiles?',
   '["Ezra","Nehemiah","Baruch","Shaphan"]',0,'Nehemiah 8:1-8',
   'Ezra read from morning until midday, and the people wept at the words.'),
  ('character','hard','Who was Jacob''s first wife, given to him by Laban''s trickery?',
   '["Rachel","Leah","Bilhah","Zilpah"]',1,'Genesis 29:23-25',
   'Laban switched Leah for Rachel; Jacob served seven more years.'),
  ('character','hard','Who was Eunice?',
   '["A deaconess in Cenchrea","John Mark''s sister","Timothy''s mother who shared her sincere faith","A widow supported by the church"]',2,'2 Timothy 1:5',
   'Timothy''s Jewish mother Eunice taught him the Scriptures from childhood.'),
  ('character','hard','Who was Phoebe?',
   '["A prophetess in Caesarea","Lydia''s business partner","A servant of the church in Cenchrea","Timothy''s aunt"]',2,'Romans 16:1-2',
   'Paul commended Phoebe, who likely carried the letter to the Romans.'),
  ('character','hard','Who was Gamaliel?',
   '["The high priest at Jesus'' trial","A tax collector in Capernaum","A Roman tribune","The Pharisee teacher who advised the council"]',3,'Acts 5:34-39',
   '"If this work is of God, you cannot overthrow it" — Gamaliel''s counsel spared the apostles.')
)
INSERT INTO bible_questions (category, difficulty, question, options, correct_index, source_ref, explanation)
SELECT n.category, n.difficulty, n.question, n.options::jsonb, n.correct_index, n.source_ref, n.explanation
FROM new_q n
WHERE NOT EXISTS (
  SELECT 1 FROM bible_questions q
  WHERE lower(btrim(q.question)) = lower(btrim(n.question))
);


WITH new_p(reference, text, blank_word, distractors) AS (
  VALUES
  ('Psalm 46:1',
   'God is our refuge and strength, a very present help in trouble.',
   'refuge','["fortress","shield","rock"]'),
  ('Romans 12:2',
   'And do not be conformed to this world, but be transformed by the renewing of your mind.',
   'transformed','["restored","redeemed","refined"]'),
  ('Galatians 5:22',
   'But the fruit of the Spirit is love, joy, peace, longsuffering, kindness, goodness, faithfulness.',
   'love','["hope","grace","mercy"]'),
  ('Ephesians 2:8',
   'For by grace you have been saved through faith, and that not of yourselves; it is the gift of God.',
   'grace','["works","mercy","love"]'),
  ('2 Timothy 3:16',
   'All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.',
   'inspiration','["revelation","declaration","interpretation"]'),
  ('1 Corinthians 10:13',
   'God is faithful, who will not allow you to be tempted beyond what you are able.',
   'tempted','["tested","troubled","shaken"]'),
  ('Matthew 11:28',
   'Come to Me, all you who labor and are heavy laden, and I will give you rest.',
   'rest','["peace","hope","joy"]'),
  ('Psalm 119:11',
   'Your word I have hidden in my heart, that I might not sin against You.',
   'heart','["mind","soul","mouth"]'),
  ('James 1:22',
   'But be doers of the word, and not hearers only, deceiving yourselves.',
   'doers','["keepers","lovers","speakers"]'),
  ('Isaiah 26:3',
   'You will keep him in perfect peace, whose mind is stayed on You, because he trusts in You.',
   'peace','["rest","hope","joy"]')
)
INSERT INTO bible_passages (reference, text, blank_word, distractors)
SELECT n.reference, n.text, n.blank_word, n.distractors::jsonb
FROM new_p n
WHERE NOT EXISTS (
  SELECT 1 FROM bible_passages p WHERE p.reference = n.reference
);


WITH new_c(name, category, difficulty, clue_1, clue_2, clue_3, clue_4, distractors, source_ref, explanation) AS (
  VALUES
  ('Joshua','old_testament','easy',
   'I served Moses from my youth.',
   'I was one of the two spies who believed God.',
   'I led Israel across the Jordan on dry ground.',
   'I declared, "As for me and my house, we will serve the Lord."',
   '["Caleb","Moses","Gideon"]','Joshua 1-24',
   'Joshua succeeded Moses and led Israel into the promised land.'),
  ('Solomon','old_testament','easy',
   'My father was Israel''s greatest king.',
   'God offered me anything — I asked for wisdom.',
   'I settled a dispute between two mothers over one living baby.',
   'I built the first temple in Jerusalem.',
   '["David","Rehoboam","Hezekiah"]','1 Kings 3-8',
   'Solomon''s wisdom and temple marked Israel''s golden age.'),
  ('Esther','character','easy',
   'I was an orphan raised by my older cousin.',
   'I became queen of Persia without revealing my people.',
   'I fasted three days before approaching the king unbidden.',
   'I was born "for such a time as this."',
   '["Ruth","Deborah","Abigail"]','Esther 2-9',
   'Esther risked her life and saved the Jews from Haman''s plot.'),
  ('Isaac','old_testament','easy',
   'My name means "laughter."',
   'My birth was promised when my parents were very old.',
   'My father bound me on an altar at Moriah.',
   'My wife Rebekah was found at a well.',
   '["Ishmael","Jacob","Esau"]','Genesis 21-26',
   'Isaac was the promised son through whom the covenant continued.'),
  ('Jacob','old_testament','easy',
   'I was born holding my twin brother''s heel.',
   'I traded a bowl of stew for a birthright.',
   'I worked fourteen years for the wife I loved.',
   'I wrestled until daybreak and received the name Israel.',
   '["Esau","Laban","Joseph"]','Genesis 25-35',
   'Jacob the schemer became Israel, father of the twelve tribes.'),
  ('Zacchaeus','new_testament','easy',
   'I was rich, but no one liked how I earned it.',
   'I was too short to see over the crowd.',
   'I climbed a sycamore tree to see Jesus pass.',
   'I promised to repay fourfold everyone I had cheated.',
   '["Matthew","Bartimaeus","Nicodemus"]','Luke 19:1-10',
   'Jesus called Zacchaeus down, and salvation came to his house that day.'),
  ('Lazarus','new_testament','easy',
   'I lived in Bethany with my two sisters.',
   'Jesus often rested at our home.',
   'Jesus wept at my tomb.',
   'I walked out still wrapped in grave clothes after four days.',
   '["Stephen","Nicodemus","Simon the leper"]','John 11',
   'Raising Lazarus revealed Jesus'' power over death itself.'),
  ('Martha','new_testament','medium',
   'I loved hosting Jesus in my home.',
   'I once complained that my sister left me to serve alone.',
   'I told Jesus my brother would not have died had He been there.',
   'I confessed, "You are the Christ, the Son of God."',
   '["Mary Magdalene","Salome","Joanna"]','Luke 10:38-42; John 11',
   'Martha''s confession stands among the strongest statements of faith in the Gospels.'),
  ('Gideon','old_testament','medium',
   'I was threshing wheat in a winepress, hiding from raiders.',
   'The Angel of the Lord called me a mighty man of valor.',
   'I tested God''s word twice with a fleece.',
   'My 300 men carried torches, trumpets, and empty pitchers.',
   '["Barak","Jephthah","Samson"]','Judges 6-7',
   'God shrank Gideon''s army so Israel would know the victory was His.'),
  ('Deborah','old_testament','medium',
   'I judged Israel under a palm tree.',
   'I was a prophetess in days when raiders ruled the roads.',
   'I summoned Barak to face Sisera''s 900 iron chariots.',
   'My victory song remembers a tent peg.',
   '["Huldah","Miriam","Jael"]','Judges 4-5',
   'Under Deborah''s leadership the land had rest for forty years.'),
  ('Hannah','old_testament','medium',
   'I wept so hard at Shiloh the priest thought I was drunk.',
   'I was taunted year after year for having no children.',
   'I vowed to give my son to the Lord all the days of his life.',
   'My boy grew up to anoint Israel''s first two kings.',
   '["Peninnah","Ruth","Rachel"]','1 Samuel 1-2',
   'Hannah''s answered prayer gave Israel the prophet Samuel.'),
  ('Boaz','old_testament','medium',
   'I owned barley fields in Bethlehem.',
   'I noticed a foreign widow gleaning behind my reapers.',
   'I redeemed her as a near kinsman.',
   'My great-grandson was King David.',
   '["Elimelech","Obed","Jesse"]','Ruth 2-4',
   'Boaz the kinsman-redeemer pictures the Redeemer who covers and restores.'),
  ('Elisha','old_testament','medium',
   'I was plowing with twelve yoke of oxen when I was called.',
   'I asked for a double portion of my master''s spirit.',
   'I told a Syrian commander to wash in the Jordan seven times.',
   'I made a borrowed iron axe head float.',
   '["Elijah","Gehazi","Jehu"]','2 Kings 2-6',
   'Elisha carried on Elijah''s ministry with twice the recorded miracles.'),
  ('Rahab','character','medium',
   'My house was built on Jericho''s wall.',
   'I hid two spies under stalks of flax.',
   'A scarlet cord in my window saved my whole family.',
   'I became an ancestor of the Messiah.',
   '["Ruth","Tamar","Jael"]','Joshua 2; Matthew 1:5',
   'Rahab''s faith placed her in the family line of Jesus.'),
  ('Nicodemus','new_testament','medium',
   'I was a Pharisee and a ruler of the Jews.',
   'I came to Jesus by night with my questions.',
   'I was told I must be born again.',
   'I helped bury Jesus with a hundred pounds of spices.',
   '["Joseph of Arimathea","Gamaliel","Caiaphas"]','John 3; John 19:39',
   'Nicodemus moved from night-time questions to public devotion at the cross.'),
  ('Andrew','new_testament','medium',
   'I was a fisherman from Bethsaida.',
   'I first followed John the Baptist.',
   'The first thing I did was bring my brother to Jesus.',
   'I found the boy with five loaves and two small fish.',
   '["Peter","Philip","James"]','John 1:40-42; John 6:8-9',
   'Andrew is remembered for one habit: bringing people to Jesus.'),
  ('Barnabas','new_testament','hard',
   'The apostles renamed me "Son of Encouragement."',
   'I sold my field and laid the money at the apostles'' feet.',
   'I vouched for Saul when everyone else feared him.',
   'I parted ways with Paul over John Mark.',
   '["Silas","Apollos","Titus"]','Acts 4:36-37; 9:27; 15:36-39',
   'Barnabas''s encouragement launched Paul''s ministry — and restored John Mark''s.'),
  ('Timothy','new_testament','hard',
   'My mother was Jewish and my father was Greek.',
   'I knew the Holy Scriptures from childhood.',
   'Paul called me his true son in the faith.',
   'I was told to let no one despise my youth.',
   '["Titus","Silas","John Mark"]','Acts 16:1-3; 1 Timothy 4:12',
   'Timothy pastored Ephesus and received Paul''s final letter.'),
  ('Jeremiah','old_testament','hard',
   'I was called as a prophet while still a youth.',
   'I am known as the weeping prophet.',
   'I was lowered into a miry cistern for speaking the truth.',
   'I bought a field while Babylon besieged the city.',
   '["Isaiah","Ezekiel","Baruch"]','Jeremiah 1; 32; 38',
   'Jeremiah preached forty years to a nation that would not listen — and kept preaching.'),
  ('Job','character','hard',
   'I lived in the land of Uz.',
   'I lost my children, wealth, and health within days.',
   'My friends sat with me in silence for seven days.',
   'I said, "I know that my Redeemer lives."',
   '["Eliphaz","Noah","Daniel"]','Job 1-2; 19:25; 42',
   'Job shows what it means to trust God without having all the answers.')
)
INSERT INTO bible_characters (name, category, difficulty, clue_1, clue_2, clue_3, clue_4, distractors, source_ref, explanation)
SELECT n.name, n.category, n.difficulty, n.clue_1, n.clue_2, n.clue_3, n.clue_4, n.distractors::jsonb, n.source_ref, n.explanation
FROM new_c n
WHERE NOT EXISTS (
  SELECT 1 FROM bible_characters c WHERE lower(c.name) = lower(n.name)
);


WITH new_m(reference, verse_snippet, full_text) AS (
  VALUES
  ('Romans 5:8','While we were still sinners, Christ died for us.',
   'But God demonstrates His own love toward us, in that while we were still sinners, Christ died for us.'),
  ('Psalm 27:1','The Lord is my light and my salvation.',
   'The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?'),
  ('Isaiah 53:5','By His stripes we are healed.',
   'But He was wounded for our transgressions, He was bruised for our iniquities; the chastisement for our peace was upon Him, and by His stripes we are healed.'),
  ('Micah 6:8','Do justly, love mercy, walk humbly.',
   'He has shown you, O man, what is good; and what does the Lord require of you but to do justly, to love mercy, and to walk humbly with your God?'),
  ('Matthew 5:16','Let your light so shine before men.',
   'Let your light so shine before men, that they may see your good works and glorify your Father in heaven.'),
  ('John 8:12','I am the light of the world.',
   'Then Jesus spoke to them again, saying, "I am the light of the world. He who follows Me shall not walk in darkness, but have the light of life."'),
  ('John 15:5','I am the vine, you are the branches.',
   'I am the vine, you are the branches. He who abides in Me, and I in him, bears much fruit; for without Me you can do nothing.'),
  ('2 Corinthians 5:17','In Christ, he is a new creation.',
   'Therefore, if anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new.'),
  ('Colossians 3:23','Do it heartily, as to the Lord.',
   'And whatever you do, do it heartily, as to the Lord and not to men.'),
  ('Hebrews 4:12','The word of God is living and powerful.',
   'For the word of God is living and powerful, and sharper than any two-edged sword, piercing even to the division of soul and spirit.'),
  ('Psalm 34:8','Taste and see that the Lord is good.',
   'Oh, taste and see that the Lord is good; blessed is the man who trusts in Him!'),
  ('Proverbs 18:10','The name of the Lord is a strong tower.',
   'The name of the Lord is a strong tower; the righteous run to it and are safe.'),
  ('Philippians 4:6','Be anxious for nothing.',
   'Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God.'),
  ('Romans 10:9','Confess with your mouth the Lord Jesus.',
   'If you confess with your mouth the Lord Jesus and believe in your heart that God has raised Him from the dead, you will be saved.'),
  ('Psalm 118:24','This is the day the Lord has made.',
   'This is the day the Lord has made; we will rejoice and be glad in it.')
)
INSERT INTO memory_card_pairs (reference, verse_snippet, full_text)
SELECT n.reference, n.verse_snippet, n.full_text
FROM new_m n
WHERE NOT EXISTS (
  SELECT 1 FROM memory_card_pairs m WHERE m.reference = n.reference
);


WITH new_s(reference, text) AS (
  VALUES
  ('Psalm 27:1',          'The Lord is my light and my salvation'),
  ('John 8:12',           'I am the light of the world'),
  ('Psalm 34:8',          'Taste and see that the Lord is good'),
  ('Proverbs 18:10',      'The name of the Lord is a strong tower'),
  ('John 15:5',           'I am the vine you are the branches'),
  ('Psalm 56:3',          'Whenever I am afraid I will trust in You'),
  ('1 John 1:9',          'If we confess our sins He is faithful and just'),
  ('Romans 12:21',        'Do not be overcome by evil but overcome evil with good'),
  ('Micah 6:8',           'Do justly love mercy and walk humbly with your God'),
  ('2 Corinthians 5:7',   'For we walk by faith not by sight'),
  ('Colossians 3:23',     'Whatever you do do it heartily as to the Lord'),
  ('Psalm 118:24',        'This is the day the Lord has made'),
  ('Nahum 1:7',           'The Lord is good a stronghold in the day of trouble'),
  ('James 4:8',           'Draw near to God and He will draw near to you'),
  ('Matthew 5:16',        'Let your light so shine before men')
)
INSERT INTO bible_verse_scrambles (reference, text)
SELECT n.reference, n.text
FROM new_s n
WHERE NOT EXISTS (
  SELECT 1 FROM bible_verse_scrambles s WHERE s.reference = n.reference
);


WITH new_e(title, description, chronological_order, approx_year_text, source_ref) AS (
  VALUES
  ('Abraham offers Isaac',
   'God provides a ram in place of Abraham''s son on Mount Moriah.',
   650,'~2050 BC','Genesis 22'),
  ('Jacob''s family settles in Egypt',
   'Joseph brings his father and brothers to Goshen during the famine.',
   950,'~1875 BC','Genesis 46-47'),
  ('Moses and the burning bush',
   'God calls Moses from a bush that burns but is not consumed.',
   1050,'~1450 BC','Exodus 3'),
  ('Forty years in the wilderness',
   'Israel wanders after refusing to enter the promised land.',
   1250,'~1440 BC','Numbers 14'),
  ('Ruth gleans in Boaz''s field',
   'A Moabite widow finds refuge — and a redeemer — in Bethlehem.',
   1450,'~1100 BC','Ruth 2'),
  ('David becomes king over Israel',
   'After Saul''s death, David is anointed king and takes Jerusalem.',
   1650,'~1010 BC','2 Samuel 5'),
  ('Elisha succeeds Elijah',
   'Elijah is taken up in a whirlwind; his mantle falls to Elisha.',
   1940,'~850 BC','2 Kings 2'),
  ('Jonah preaches to Nineveh',
   'A reluctant prophet is swallowed by a great fish; then Nineveh repents.',
   1970,'~780 BC','Jonah 1-3'),
  ('The fiery furnace',
   'Shadrach, Meshach, and Abed-Nego survive Nebuchadnezzar''s furnace.',
   2220,'~590 BC','Daniel 3'),
  ('Jesus feeds the five thousand',
   'Five loaves and two fish feed a multitude, with twelve baskets left over.',
   3150,'~AD 29','John 6'),
  ('Philip and the Ethiopian',
   'An official believes and is baptized on the desert road to Gaza.',
   3350,'~AD 34','Acts 8'),
  ('Paul shipwrecked on Malta',
   'En route to Caesar, Paul''s ship runs aground; all 276 aboard survive.',
   3550,'~AD 60','Acts 27-28')
)
INSERT INTO bible_events (title, description, chronological_order, approx_year_text, source_ref)
SELECT n.title, n.description, n.chronological_order, n.approx_year_text, n.source_ref
FROM new_e n
WHERE NOT EXISTS (
  SELECT 1 FROM bible_events e WHERE lower(e.title) = lower(n.title)
);

