
INSERT INTO bible_questions (category, difficulty, question, options, correct_index, source_ref, explanation) VALUES

('old_testament','easy','Who was the first man God created?',
 '["Cain","Noah","Adam","Enoch"]'::jsonb,2,'Genesis 2:7',
 'The Lord formed Adam from the dust of the ground and breathed life into his nostrils (Genesis 2:7).'),
('old_testament','easy','What did God create on the first day?',
 '["The sun","Animals","Light","Plants"]'::jsonb,2,'Genesis 1:3',
 'On day one God said, “Let there be light,” and separated light from darkness (Genesis 1:3-5).'),
('old_testament','easy','Where did God place Adam and Eve?',
 '["Mount Sinai","Garden of Eden","Land of Ur","Bethel"]'::jsonb,1,'Genesis 2:8',
 'God planted a garden eastward in Eden and put Adam there to tend it (Genesis 2:8, 15).'),
('old_testament','easy','In what form did Satan tempt Eve?',
 '["A serpent","A lion","An angel","A goat"]'::jsonb,0,'Genesis 3:1',
 'The serpent — “more cunning than any beast of the field” — deceived Eve (Genesis 3:1, 13).'),
('old_testament','easy','On what mountain did Noah''s ark come to rest?',
 '["Sinai","Carmel","Ararat","Hermon"]'::jsonb,2,'Genesis 8:4',
 'The ark rested on the mountains of Ararat in the seventh month (Genesis 8:4).'),
('old_testament','easy','What sign of the covenant did God give after the flood?',
 '["A star","A dove","A rainbow","An altar"]'::jsonb,2,'Genesis 9:13',
 'God set His rainbow in the cloud as the sign of His covenant never again to flood the earth (Genesis 9:13).'),
('old_testament','easy','What tower did men build that God scattered?',
 '["Tower of David","Tower of Babel","Tower of Shechem","Tower of Siloam"]'::jsonb,1,'Genesis 11:9',
 'At Babel God confused the people''s language and scattered them over the face of the earth (Genesis 11:7-9).'),
('old_testament','easy','Who was turned into a pillar of salt while fleeing Sodom?',
 '["Lot''s wife","Sarah","Hagar","Rebekah"]'::jsonb,0,'Genesis 19:26',
 'Lot''s wife looked back from behind him toward Sodom and became a pillar of salt (Genesis 19:26).'),
('old_testament','easy','What was the name of Abraham''s son of promise?',
 '["Ishmael","Isaac","Esau","Jacob"]'::jsonb,1,'Genesis 21:3',
 'Sarah bore Abraham a son in his old age, and he called his name Isaac (Genesis 21:3).'),
('old_testament','easy','What did Jacob see in a dream at Bethel?',
 '["A burning bush","A ladder to heaven","A whirlwind","A scroll"]'::jsonb,1,'Genesis 28:12',
 'Jacob dreamed of a ladder set on the earth whose top reached to heaven, with angels ascending and descending (Genesis 28:12).'),
('old_testament','easy','How many sons did Jacob have?',
 '["Ten","Twelve","Seven","Twenty"]'::jsonb,1,'Genesis 35:22-26',
 'Jacob had twelve sons, who became the fathers of the twelve tribes of Israel (Genesis 35:22-26).'),
('old_testament','easy','What colorful garment did Jacob give Joseph?',
 '["A linen ephod","A coat of many colors","A purple robe","A leather belt"]'::jsonb,1,'Genesis 37:3',
 'Israel loved Joseph more than all his children and made him a tunic of many colors (Genesis 37:3).'),
('old_testament','easy','What food did God rain from heaven in the wilderness?',
 '["Quail only","Bread","Manna","Honey"]'::jsonb,2,'Exodus 16:14-15',
 'Each morning God provided manna — small, round, like coriander seed — for Israel to gather (Exodus 16:14-15, 31).'),
('old_testament','easy','From what kind of bush did God speak to Moses?',
 '["A fig tree","A burning bush","An olive tree","A cedar"]'::jsonb,1,'Exodus 3:2',
 'The Angel of the Lord appeared to Moses in a flame of fire from the midst of a bush that did not burn up (Exodus 3:2).'),
('old_testament','easy','Through which sea did Israel pass on dry ground?',
 '["Dead Sea","Sea of Galilee","Red Sea","Mediterranean"]'::jsonb,2,'Exodus 14:21',
 'God drove the Red Sea back by a strong east wind, and Israel crossed on dry ground (Exodus 14:21-22).'),
('old_testament','easy','Where did Moses receive the Ten Commandments?',
 '["Mount Sinai","Mount Carmel","Mount Hor","Mount Nebo"]'::jsonb,0,'Exodus 19:20; 20',
 'The Lord came down on Mount Sinai and gave Moses the Ten Commandments written on tablets of stone (Exodus 19:20; 20:1-17).'),
('old_testament','easy','Who succeeded Moses as leader of Israel?',
 '["Caleb","Joshua","Aaron","Phinehas"]'::jsonb,1,'Joshua 1:1-2',
 'After Moses died, the Lord told Joshua son of Nun to lead Israel across the Jordan into the promised land (Joshua 1:1-2).'),
('old_testament','easy','What city''s walls fell when Israel shouted?',
 '["Ai","Jericho","Hebron","Bethel"]'::jsonb,1,'Joshua 6:20',
 'When the priests blew the trumpets and the people shouted, the walls of Jericho fell down flat (Joshua 6:20).'),
('old_testament','easy','Which judge had supernatural strength from his hair?',
 '["Gideon","Samson","Jephthah","Ehud"]'::jsonb,1,'Judges 16:17',
 'Samson''s strength was tied to his Nazirite vow; when Delilah cut his hair, his strength left him (Judges 16:17-19).'),
('old_testament','easy','Who anointed the boy David as Israel''s next king?',
 '["Nathan","Samuel","Eli","Zadok"]'::jsonb,1,'1 Samuel 16:13',
 'Samuel anointed David in the midst of his brothers, and the Spirit of the Lord came upon him from that day forward (1 Samuel 16:13).'),
('old_testament','easy','What was Goliath?',
 '["A Moabite king","A Philistine giant","An Egyptian general","An Assyrian spy"]'::jsonb,1,'1 Samuel 17:4',
 'Goliath of Gath, a champion of the Philistines, stood six cubits and a span tall and defied Israel (1 Samuel 17:4-10).'),
('old_testament','easy','Whose son was Solomon?',
 '["Saul","David","Samuel","Jehoshaphat"]'::jsonb,1,'1 Kings 1:11',
 'Solomon was the son of King David and Bathsheba and succeeded David on the throne (1 Kings 1:11; 2:12).'),
('old_testament','easy','What did God send to feed Elijah by the brook Cherith?',
 '["Doves","Ravens","Eagles","Sparrows"]'::jsonb,1,'1 Kings 17:6',
 'Ravens brought Elijah bread and meat in the morning and evening while he hid by the brook Cherith (1 Kings 17:6).'),
('old_testament','easy','Who was Elijah''s successor?',
 '["Isaiah","Elisha","Hosea","Micaiah"]'::jsonb,1,'2 Kings 2:9',
 'Elisha asked for a double portion of Elijah''s spirit and received it when Elijah was taken up (2 Kings 2:9-15).'),
('old_testament','easy','Whose donkey spoke aloud to him?',
 '["Balaam","Saul","Achan","Korah"]'::jsonb,0,'Numbers 22:28',
 'The Lord opened the mouth of Balaam''s donkey, and she rebuked the prophet for striking her (Numbers 22:28).'),
('old_testament','easy','Which book of the Bible comes first?',
 '["Exodus","Genesis","Leviticus","Job"]'::jsonb,1,'Genesis 1:1',
 'Genesis is the first book and opens with “In the beginning God created the heavens and the earth” (Genesis 1:1).'),
('old_testament','easy','How many of every kind of clean animal did Noah take?',
 '["One pair","Two pairs","Seven pairs","Ten pairs"]'::jsonb,2,'Genesis 7:2',
 'God told Noah to take seven each of every clean animal and a male and female of the unclean (Genesis 7:2-3).'),
('old_testament','easy','What did God call the dry land He gathered together?',
 '["Skies","Earth","Sea","Land of Eden"]'::jsonb,1,'Genesis 1:10',
 'God called the dry land Earth, and the gathering of the waters He called Seas (Genesis 1:10).'),
('old_testament','easy','Who killed his brother Abel?',
 '["Seth","Cain","Lamech","Esau"]'::jsonb,1,'Genesis 4:8',
 'Cain rose up against his brother Abel and killed him in the field out of jealousy (Genesis 4:8).'),
('old_testament','easy','What did God create on the seventh day?',
 '["Stars","Animals","Nothing — He rested","Man"]'::jsonb,2,'Genesis 2:2',
 'On the seventh day God ended His work, and He rested — blessing and sanctifying the day (Genesis 2:2-3).'),

('old_testament','medium','How old was Methuselah when he died?',
 '["777","800","930","969"]'::jsonb,3,'Genesis 5:27',
 'Methuselah lived 969 years — the longest life recorded in Scripture — and then he died (Genesis 5:27).'),
('old_testament','medium','What did Esau sell to Jacob for a bowl of stew?',
 '["His sword","His birthright","His coat","His land"]'::jsonb,1,'Genesis 25:33',
 'Esau swore an oath and sold his birthright to Jacob for bread and a meal of lentils (Genesis 25:33-34).'),
('old_testament','medium','Where did Jacob wrestle with God?',
 '["Bethel","Peniel","Shechem","Mahanaim"]'::jsonb,1,'Genesis 32:30',
 'Jacob called the place Peniel: “For I have seen God face to face, and my life is preserved” (Genesis 32:30).'),
('old_testament','medium','What new name did God give Jacob?',
 '["Joshua","Israel","Ishmael","Reuben"]'::jsonb,1,'Genesis 32:28',
 'God renamed Jacob Israel, “for you have struggled with God and with men, and have prevailed” (Genesis 32:28).'),
('old_testament','medium','Which Egyptian official''s wife falsely accused Joseph?',
 '["Pharaoh''s","Potiphar''s","The baker''s","The cupbearer''s"]'::jsonb,1,'Genesis 39:7',
 'Potiphar''s wife lied about Joseph after he refused her advances, and Joseph was imprisoned (Genesis 39:7-20).'),
('old_testament','medium','What was the tenth and final plague on Egypt?',
 '["Locusts","Hail","Death of the firstborn","Darkness"]'::jsonb,2,'Exodus 12:29',
 'At midnight the Lord struck the firstborn of every Egyptian home, and Pharaoh finally let Israel go (Exodus 12:29-32).'),
('old_testament','medium','What was the portable tent of worship called?',
 '["Synagogue","Tabernacle","Holy Place","Pavilion"]'::jsonb,1,'Exodus 25-26',
 'The Tabernacle was God''s dwelling among Israel — a portable sanctuary built to His exact pattern (Exodus 25:8-9).'),
('old_testament','medium','What did Aaron make while Moses was on Sinai?',
 '["A bronze altar","A golden calf","An iron chariot","A wooden ark"]'::jsonb,1,'Exodus 32:4',
 'Aaron formed a golden calf from the people''s earrings, and they worshiped it as their god (Exodus 32:4).'),
('old_testament','medium','How many spies did Moses send into Canaan?',
 '["Seven","Ten","Twelve","Seventy"]'::jsonb,2,'Numbers 13:1-16',
 'Moses sent twelve spies — one from each tribe — to scout the land of Canaan (Numbers 13:1-16).'),
('old_testament','medium','Which two faithful spies urged Israel to take the land?',
 '["Caleb and Joshua","Aaron and Eleazar","Phinehas and Caleb","Joshua and Hur"]'::jsonb,0,'Numbers 14:6-9',
 'Caleb and Joshua tore their clothes and urged Israel to trust God to give them the land (Numbers 14:6-9).'),
('old_testament','medium','Which judge defeated the Midianites with 300 men?',
 '["Samson","Ehud","Gideon","Othniel"]'::jsonb,2,'Judges 7',
 'Gideon defeated the Midianite army of thousands with just 300 men and torches inside pitchers (Judges 7:16-22).'),
('old_testament','medium','Which woman drove a tent peg through Sisera''s temple?',
 '["Deborah","Jael","Hannah","Abigail"]'::jsonb,1,'Judges 4:21',
 'Jael, wife of Heber, drove a tent peg through the temple of the fleeing commander Sisera (Judges 4:21).'),
('old_testament','medium','Which prophetess judged Israel in the time of Barak?',
 '["Miriam","Deborah","Huldah","Hannah"]'::jsonb,1,'Judges 4:4',
 'Deborah, a prophetess, was judging Israel and went with Barak into battle against Sisera (Judges 4:4-9).'),
('old_testament','medium','Who was Hannah''s son?',
 '["Samuel","Saul","Solomon","Samson"]'::jsonb,0,'1 Samuel 1:20',
 'Hannah prayed for a child and God gave her Samuel, whom she dedicated to the Lord (1 Samuel 1:20-28).'),
('old_testament','medium','Who anointed Solomon as king of Israel?',
 '["Nathan and Zadok","Samuel","Elijah","Abiathar"]'::jsonb,0,'1 Kings 1:38-39',
 'Zadok the priest and Nathan the prophet anointed Solomon king at Gihon (1 Kings 1:38-39).'),
('old_testament','medium','Who was Solomon''s mother?',
 '["Michal","Abigail","Bathsheba","Maacah"]'::jsonb,2,'1 Kings 1:11',
 'Bathsheba was Solomon''s mother and interceded for him with David (1 Kings 1:11-31).'),
('old_testament','medium','What did Solomon ask God for at Gibeon?',
 '["Wealth","Long life","Wisdom","Victory"]'::jsonb,2,'1 Kings 3:9',
 'Solomon asked for an understanding heart to judge God''s people, and the request pleased the Lord (1 Kings 3:9-10).'),
('old_testament','medium','Which prophet confronted 450 prophets of Baal on Carmel?',
 '["Elisha","Elijah","Micaiah","Jonah"]'::jsonb,1,'1 Kings 18',
 'Elijah challenged Baal''s prophets on Mount Carmel; God answered with fire and consumed the sacrifice (1 Kings 18:36-39).'),
('old_testament','medium','Which king of Israel set up two golden calves at Bethel and Dan?',
 '["Ahab","Omri","Jeroboam","Jehu"]'::jsonb,2,'1 Kings 12:28-29',
 'Jeroboam I made two golden calves to keep his northern subjects from worshiping in Jerusalem (1 Kings 12:28-29).'),
('old_testament','medium','Whom did Elisha heal of leprosy?',
 '["Uzziah","Naaman","Gehazi","Hezekiah"]'::jsonb,1,'2 Kings 5:10-14',
 'Naaman the Syrian commander was healed of leprosy by washing seven times in the Jordan (2 Kings 5:10-14).'),
('old_testament','medium','Which Babylonian king destroyed Jerusalem''s first temple?',
 '["Belshazzar","Nebuchadnezzar","Cyrus","Darius"]'::jsonb,1,'2 Kings 25:8-9',
 'Nebuchadnezzar''s captain Nebuzaradan burned the temple, the palace, and all of Jerusalem in 586 BC (2 Kings 25:8-9).'),
('old_testament','medium','Who led the first wave of exiles back to Jerusalem?',
 '["Ezra","Nehemiah","Zerubbabel","Mordecai"]'::jsonb,2,'Ezra 2:2',
 'Zerubbabel led the first return from Babylon and laid the foundation of the second temple (Ezra 2:2; 3:8-10).'),
('old_testament','medium','Who rebuilt the walls of Jerusalem in 52 days?',
 '["Ezra","Nehemiah","Zerubbabel","Hezekiah"]'::jsonb,1,'Nehemiah 6:15',
 'Under Nehemiah''s leadership the walls of Jerusalem were completed in 52 days, despite fierce opposition (Nehemiah 6:15).'),
('old_testament','medium','What was Daniel''s Babylonian name?',
 '["Shadrach","Belteshazzar","Abednego","Meshach"]'::jsonb,1,'Daniel 1:7',
 'The chief eunuch gave Daniel the Babylonian name Belteshazzar (Daniel 1:7).'),
('old_testament','medium','Which three young men survived the fiery furnace?',
 '["Daniel, Hananiah, Azariah","Shadrach, Meshach, Abednego","Belteshazzar, Hananiah, Mishael","Jeremiah, Baruch, Ebed-Melech"]'::jsonb,1,'Daniel 3:23-27',
 'Shadrach, Meshach, and Abednego walked unharmed in the fiery furnace, joined by a fourth like the Son of God (Daniel 3:25-27).'),
('old_testament','medium','Which prophet was sent to Nineveh?',
 '["Amos","Jonah","Obadiah","Joel"]'::jsonb,1,'Jonah 1:2',
 'God sent Jonah to preach against the wickedness of Nineveh (Jonah 1:2; 3:1-4).'),
('old_testament','medium','Who said "Here am I! Send me" to God''s call?',
 '["Jeremiah","Isaiah","Ezekiel","Samuel"]'::jsonb,1,'Isaiah 6:8',
 'Isaiah, after seeing the Lord''s holiness in the temple vision, responded, “Here am I! Send me” (Isaiah 6:8).'),
('old_testament','medium','Who said "Curse God and die" to a suffering man?',
 '["Job''s friend Eliphaz","Job''s wife","Bildad","Job himself"]'::jsonb,1,'Job 2:9',
 'Job''s wife told him to “curse God and die,” but Job answered that we receive good and adversity from God (Job 2:9-10).'),

('old_testament','hard','How many years did Solomon reign over Israel?',
 '["20","30","40","50"]'::jsonb,2,'1 Kings 11:42',
 'Solomon reigned in Jerusalem over all Israel forty years (1 Kings 11:42).'),
('old_testament','hard','How tall was Goliath?',
 '["Four cubits","Five cubits","Six cubits and a span","Eight cubits"]'::jsonb,2,'1 Samuel 17:4',
 'Goliath stood six cubits and a span — roughly nine feet nine inches (1 Samuel 17:4).'),
('old_testament','hard','How many wives did Solomon have?',
 '["300","500","700","1000"]'::jsonb,2,'1 Kings 11:3',
 'Solomon had 700 wives, princesses, and 300 concubines — and they turned his heart from God (1 Kings 11:3-4).'),
('old_testament','hard','Who was the last king of Judah?',
 '["Jehoiakim","Jehoiachin","Zedekiah","Josiah"]'::jsonb,2,'2 Kings 25:7',
 'Zedekiah was the last king of Judah; Nebuchadnezzar blinded him and led him to Babylon (2 Kings 25:7).'),
('old_testament','hard','How many years was Judah in Babylonian captivity?',
 '["40","50","70","100"]'::jsonb,2,'Jeremiah 25:11',
 'Jeremiah prophesied that the nations would serve the king of Babylon seventy years (Jeremiah 25:11).'),
('old_testament','hard','Who was the priest-king of Salem to whom Abraham gave a tenth?',
 '["Melchizedek","Eli","Phinehas","Zadok"]'::jsonb,0,'Genesis 14:18-20',
 'Melchizedek, king of Salem and priest of God Most High, blessed Abraham who gave him a tithe of all (Genesis 14:18-20).'),
('old_testament','hard','Who was Abraham''s nephew that settled near Sodom?',
 '["Eliezer","Lot","Laban","Hagar"]'::jsonb,1,'Genesis 13:12',
 'Lot chose the well-watered Jordan plain and dwelt in the cities of the plain, pitching his tent toward Sodom (Genesis 13:12).'),
('old_testament','hard','What was Sarai''s name changed to by God?',
 '["Sarah","Mara","Rachel","Bilhah"]'::jsonb,0,'Genesis 17:15',
 'God said, “As for Sarai your wife, you shall not call her name Sarai, but Sarah shall be her name” (Genesis 17:15).'),
('old_testament','hard','How old was Abraham when Isaac was born?',
 '["75","85","100","120"]'::jsonb,2,'Genesis 21:5',
 'Abraham was one hundred years old when his son Isaac was born to him (Genesis 21:5).'),
('old_testament','hard','Who was the father of Methuselah?',
 '["Jared","Enoch","Lamech","Noah"]'::jsonb,1,'Genesis 5:21',
 'Enoch fathered Methuselah and walked with God for 300 years before God took him (Genesis 5:21-24).'),
('old_testament','hard','Who built a city and named it after his son Enoch?',
 '["Seth","Cain","Lamech","Tubal-cain"]'::jsonb,1,'Genesis 4:17',
 'Cain built a city after fleeing as a fugitive and named it after his son Enoch (Genesis 4:17).'),
('old_testament','hard','Which judge was a left-handed Benjamite who killed Eglon?',
 '["Othniel","Ehud","Shamgar","Jephthah"]'::jsonb,1,'Judges 3:15-21',
 'Ehud, a left-handed man of Benjamin, hid a dagger and assassinated the Moabite king Eglon (Judges 3:15-21).'),
('old_testament','hard','Whom did King Saul consult through the witch of En Dor?',
 '["David","Samuel","Jonathan","Eli"]'::jsonb,1,'1 Samuel 28:11-15',
 'The medium at En Dor brought up Samuel, who prophesied Saul''s defeat and death the next day (1 Samuel 28:11-19).'),
('old_testament','hard','Who was David''s rebellious son who tried to seize the throne?',
 '["Solomon","Adonijah","Absalom","Amnon"]'::jsonb,2,'2 Samuel 15',
 'Absalom stole the hearts of the men of Israel and proclaimed himself king at Hebron (2 Samuel 15:1-12).'),
('old_testament','hard','Which prophet confronted David over Bathsheba?',
 '["Gad","Nathan","Samuel","Ahijah"]'::jsonb,1,'2 Samuel 12:7',
 'Nathan rebuked David with the parable of the ewe lamb and declared, “You are the man!” (2 Samuel 12:7).'),
('old_testament','hard','Who succeeded Aaron as high priest?',
 '["Eli","Eleazar","Phinehas","Zadok"]'::jsonb,1,'Numbers 20:28',
 'Moses transferred the priestly garments to Eleazar, Aaron''s son, atop Mount Hor (Numbers 20:28).'),
('old_testament','hard','Which king of Judah was eight years old when he began to reign?',
 '["Hezekiah","Josiah","Joash","Manasseh"]'::jsonb,1,'2 Kings 22:1',
 'Josiah became king at eight years old and reigned thirty-one years in Jerusalem (2 Kings 22:1).'),
('old_testament','hard','Which longest chapter in the Bible is an acrostic on God''s Word?',
 '["Psalm 23","Psalm 100","Psalm 119","Psalm 150"]'::jsonb,2,'Psalm 119',
 'Psalm 119 is the longest chapter in Scripture — 176 verses, organized as an acrostic exalting God''s Word.'),
('old_testament','hard','Which book begins with "Vanity of vanities"?',
 '["Job","Proverbs","Ecclesiastes","Song of Solomon"]'::jsonb,2,'Ecclesiastes 1:2',
 'The Preacher opens, “Vanity of vanities, all is vanity,” reflecting on life apart from God (Ecclesiastes 1:2).'),
('old_testament','hard','Which prophet was a herdsman from Tekoa?',
 '["Hosea","Amos","Micah","Habakkuk"]'::jsonb,1,'Amos 1:1; 7:14',
 'Amos was a sheepbreeder from Tekoa whom God called to prophesy against Israel (Amos 1:1; 7:14-15).'),
('old_testament','hard','What does "Immanuel" mean?',
 '["The Lord saves","God with us","Anointed One","Prince of Peace"]'::jsonb,1,'Isaiah 7:14; Matthew 1:23',
 '“Immanuel” means “God with us” — Isaiah''s sign and Matthew''s identification of Christ (Isaiah 7:14; Matthew 1:23).'),
('old_testament','hard','Who prophesied that Cyrus would let Israel return?',
 '["Daniel","Isaiah","Jeremiah","Ezekiel"]'::jsonb,1,'Isaiah 44:28',
 'Isaiah named Cyrus by name about 150 years before Cyrus issued the decree for Israel to return (Isaiah 44:28-45:1).'),
('old_testament','hard','What did Belshazzar see written on the wall?',
 '["MENE, MENE, TEKEL, UPHARSIN","HOLY, HOLY, HOLY","ALPHA, OMEGA","SHALOM, SHALOM"]'::jsonb,0,'Daniel 5:25',
 'The hand wrote MENE, MENE, TEKEL, UPHARSIN — God had numbered and ended Belshazzar''s kingdom (Daniel 5:25-28).'),
('old_testament','hard','Which prophet''s unfaithful wife pictured Israel''s idolatry?',
 '["Hosea","Amos","Joel","Malachi"]'::jsonb,0,'Hosea 1:2',
 'God told Hosea to marry Gomer, a woman of harlotry, as a living picture of Israel''s spiritual adultery (Hosea 1:2-3).'),
('old_testament','hard','Who was Jeremiah''s scribe?',
 '["Ezra","Baruch","Mordecai","Daniel"]'::jsonb,1,'Jeremiah 36:4',
 'Baruch the son of Neriah wrote on a scroll all the words Jeremiah dictated from the Lord (Jeremiah 36:4).'),
('old_testament','hard','Who slew his thousand Philistines with a jawbone?',
 '["Samson","David","Jonathan","Shamgar"]'::jsonb,0,'Judges 15:15-16',
 'Samson found a fresh jawbone of a donkey and killed a thousand men with it (Judges 15:15-16).'),
('old_testament','hard','Who hid the boy Joash from Athaliah for six years?',
 '["Jehoiada","Jehosheba","Huldah","Zechariah"]'::jsonb,1,'2 Kings 11:2-3',
 'Jehosheba, sister of King Ahaziah, hid Joash in the temple for six years while Athaliah reigned (2 Kings 11:2-3).'),

('new_testament','easy','What angel announced Jesus'' birth to Mary?',
 '["Michael","Gabriel","Raphael","Uriel"]'::jsonb,1,'Luke 1:26-27',
 'The angel Gabriel was sent from God to Nazareth to announce Jesus'' birth to the virgin Mary (Luke 1:26-27).'),
('new_testament','easy','Who was Jesus'' adoptive earthly father?',
 '["Zacharias","Joseph","Simeon","Nicodemus"]'::jsonb,1,'Matthew 1:18-25',
 'Joseph, a carpenter from Nazareth, was the husband of Mary and the legal father of Jesus (Matthew 1:18-25).'),
('new_testament','easy','What three gifts did the Magi bring Jesus?',
 '["Bread, wine, oil","Gold, frankincense, myrrh","Silver, spices, perfume","Linen, gold, jewels"]'::jsonb,1,'Matthew 2:11',
 'The wise men opened their treasures and presented Him gold, frankincense, and myrrh (Matthew 2:11).'),
('new_testament','easy','Where did Mary and Joseph flee to escape Herod?',
 '["Egypt","Syria","Greece","Cyprus"]'::jsonb,0,'Matthew 2:13-14',
 'An angel warned Joseph in a dream to take the Child and His mother and flee to Egypt (Matthew 2:13-14).'),
('new_testament','easy','How old was Jesus when He stayed behind in the temple?',
 '["Eight","Ten","Twelve","Fifteen"]'::jsonb,2,'Luke 2:42',
 'When Jesus was twelve years old, He stayed in Jerusalem to listen and ask questions in the temple (Luke 2:42-46).'),
('new_testament','easy','How many loaves and fish fed the five thousand?',
 '["3 loaves, 2 fish","5 loaves, 2 fish","7 loaves, 5 fish","12 loaves, 7 fish"]'::jsonb,1,'John 6:9',
 'A boy''s five barley loaves and two small fish fed the multitude with twelve baskets left over (John 6:9-13).'),
('new_testament','easy','What is the shortest verse in the Bible?',
 '["God is love","Jesus wept","Rejoice always","Pray without ceasing"]'::jsonb,1,'John 11:35',
 '“Jesus wept” (John 11:35) — two words in English — comes at Lazarus'' tomb.'),
('new_testament','easy','How many days was Lazarus dead before Jesus raised him?',
 '["1","2","4","7"]'::jsonb,2,'John 11:17',
 'When Jesus arrived, Lazarus had already been in the tomb four days (John 11:17).'),
('new_testament','easy','How many silver pieces did Judas receive to betray Jesus?',
 '["10","20","30","50"]'::jsonb,2,'Matthew 26:15',
 'The chief priests counted out to Judas thirty pieces of silver to hand Jesus over (Matthew 26:15).'),
('new_testament','easy','How many times did Peter deny Jesus?',
 '["One","Two","Three","Seven"]'::jsonb,2,'Matthew 26:69-75',
 'Peter denied knowing Jesus three times before the rooster crowed, just as Jesus had foretold (Matthew 26:69-75).'),
('new_testament','easy','On what day did Jesus rise from the dead?',
 '["Second day","Third day","Fifth day","Seventh day"]'::jsonb,1,'Matthew 16:21; 1 Corinthians 15:4',
 'Jesus foretold that He would be raised the third day, and the apostles preached this as central to the gospel (1 Corinthians 15:4).'),
('new_testament','easy','From what mountain did Jesus ascend to heaven?',
 '["Sinai","Zion","Mount of Olives","Hermon"]'::jsonb,2,'Acts 1:12',
 'After speaking with His disciples, Jesus ascended from the Mount of Olives, near Jerusalem (Acts 1:9-12).'),
('new_testament','easy','Who said "I am the way, the truth, and the life"?',
 '["Peter","Paul","Jesus","John"]'::jsonb,2,'John 14:6',
 'Jesus told Thomas, “I am the way, the truth, and the life. No one comes to the Father except through Me” (John 14:6).'),
('new_testament','easy','Where did the Holy Spirit fall on the disciples at Pentecost?',
 '["Bethany","Nazareth","Jerusalem","Capernaum"]'::jsonb,2,'Acts 2:1-4',
 'The disciples were all gathered in one place in Jerusalem when the Holy Spirit came at Pentecost (Acts 2:1-4).'),
('new_testament','easy','Who was the first Christian martyr?',
 '["Stephen","James","Peter","Paul"]'::jsonb,0,'Acts 7:59',
 'Stephen was stoned to death after preaching boldly before the Sanhedrin, becoming the church''s first martyr (Acts 7:59-60).'),
('new_testament','easy','Which evangelist baptized the Ethiopian eunuch?',
 '["Peter","Philip","Stephen","Barnabas"]'::jsonb,1,'Acts 8:38',
 'Philip explained Isaiah''s prophecy to the Ethiopian official, then baptized him in nearby water (Acts 8:30-38).'),
('new_testament','easy','Who was the Roman centurion Peter baptized?',
 '["Cornelius","Julius","Pilate","Felix"]'::jsonb,0,'Acts 10:1-48',
 'Peter, sent by a vision, preached to Cornelius and his household — the first Gentile believers baptized (Acts 10:1-48).'),
('new_testament','easy','Who was Paul''s early ministry companion to Cyprus?',
 '["Silas","Timothy","Barnabas","Titus"]'::jsonb,2,'Acts 13:2',
 'The Spirit set apart Barnabas and Saul (Paul) for the work, and they sailed first to Cyprus (Acts 13:2-4).'),
('new_testament','easy','Which Gospel author was a physician?',
 '["Matthew","Mark","Luke","John"]'::jsonb,2,'Colossians 4:14',
 'Paul calls Luke “the beloved physician,” and Luke wrote both the third Gospel and Acts (Colossians 4:14).'),
('new_testament','easy','Of ten lepers healed, how many returned to thank Jesus?',
 '["One","Three","Five","All ten"]'::jsonb,0,'Luke 17:15-19',
 'Only one — a Samaritan — returned, fell at Jesus'' feet, and gave thanks (Luke 17:15-19).'),
('new_testament','easy','Where was Jesus crucified?',
 '["Mount of Olives","Bethlehem","Golgotha","Jericho"]'::jsonb,2,'John 19:17',
 'Jesus was crucified at Golgotha (called Calvary in Latin), meaning “the Place of a Skull” (John 19:17).'),
('new_testament','easy','Who was the first witness of Jesus'' resurrection?',
 '["Peter","Mary Magdalene","John","Thomas"]'::jsonb,1,'John 20:14-18',
 'Mary Magdalene was the first to see the risen Lord and was sent to tell the disciples (John 20:14-18).'),
('new_testament','easy','Which disciple doubted until he saw Jesus'' wounds?',
 '["Andrew","Thomas","Philip","Bartholomew"]'::jsonb,1,'John 20:25-28',
 'Thomas refused to believe until he saw the nail prints — then declared, “My Lord and my God!” (John 20:25-28).'),
('new_testament','easy','Where was John when he received Revelation?',
 '["Ephesus","Patmos","Antioch","Rome"]'::jsonb,1,'Revelation 1:9',
 'John was on the island called Patmos for the word of God and the testimony of Jesus Christ (Revelation 1:9).'),
('new_testament','easy','How many churches are addressed in Revelation 2-3?',
 '["Five","Seven","Ten","Twelve"]'::jsonb,1,'Revelation 2-3',
 'Christ addresses seven churches in Asia: Ephesus, Smyrna, Pergamos, Thyatira, Sardis, Philadelphia, and Laodicea.'),
('new_testament','easy','Which sister of Lazarus sat at Jesus'' feet?',
 '["Martha","Mary","Joanna","Salome"]'::jsonb,1,'Luke 10:39',
 'Mary sat at Jesus'' feet and heard His word, while Martha was distracted with much serving (Luke 10:39-40).'),
('new_testament','easy','Who carried Jesus'' cross?',
 '["Joseph of Arimathea","Simon of Cyrene","Nicodemus","Peter"]'::jsonb,1,'Mark 15:21',
 'They compelled Simon of Cyrene, the father of Alexander and Rufus, to bear Jesus'' cross (Mark 15:21).'),
('new_testament','easy','Who placed Jesus in a new tomb?',
 '["Peter","Joseph of Arimathea","Nicodemus","Simon Peter"]'::jsonb,1,'Matthew 27:57-60',
 'Joseph of Arimathea, a rich disciple, laid Jesus in his own new tomb hewn out of rock (Matthew 27:57-60).'),
('new_testament','easy','At what wedding did Jesus turn water into wine?',
 '["Bethany","Cana","Nain","Capernaum"]'::jsonb,1,'John 2:1-11',
 'At a wedding in Cana of Galilee, Jesus performed His first miraculous sign (John 2:1-11).'),
('new_testament','easy','Which apostle is called "the Rock"?',
 '["Andrew","Peter","James","John"]'::jsonb,1,'Matthew 16:18',
 'Jesus said, “You are Peter, and on this rock I will build My church” — Peter''s name means “rock” (Matthew 16:18).'),

('new_testament','medium','What did Peter answer when Jesus asked "Who do you say I am?"',
 '["A great prophet","Elijah returned","The Christ, the Son of the living God","John the Baptist"]'::jsonb,2,'Matthew 16:16',
 'Peter answered, “You are the Christ, the Son of the living God” — a revelation from the Father (Matthew 16:16-17).'),
('new_testament','medium','Who appeared with Jesus at the Transfiguration?',
 '["Abraham and David","Moses and Elijah","Enoch and Elijah","Samuel and Elijah"]'::jsonb,1,'Matthew 17:3',
 'On the high mountain Moses and Elijah appeared, talking with Jesus about His coming departure (Matthew 17:3; Luke 9:31).'),
('new_testament','medium','How many beatitudes does Jesus give in Matthew 5?',
 '["Five","Seven","Eight","Ten"]'::jsonb,2,'Matthew 5:3-10',
 'Matthew records eight blessed-are statements opening the Sermon on the Mount (Matthew 5:3-10).'),
('new_testament','medium','What did Jesus call the Pharisees in Matthew 23?',
 '["Lost sheep","Whitewashed tombs","Wolves in sheep''s clothing","Salt of the earth"]'::jsonb,1,'Matthew 23:27',
 'Jesus compared them to whitewashed tombs — beautiful outside but full of dead men''s bones inside (Matthew 23:27).'),
('new_testament','medium','Which parable describes a son who left and returned to his father?',
 '["The Sower","The Prodigal Son","The Good Samaritan","The Talents"]'::jsonb,1,'Luke 15:11-32',
 'The prodigal son squandered his inheritance, returned in repentance, and was welcomed home with a feast (Luke 15:11-32).'),
('new_testament','medium','Which parable answers "Who is my neighbor?"',
 '["The Lost Sheep","The Good Samaritan","The Two Builders","The Mustard Seed"]'::jsonb,1,'Luke 10:30-37',
 'Jesus told of a Samaritan who showed mercy to a wounded stranger — defining a neighbor by action (Luke 10:30-37).'),
('new_testament','medium','What did Jesus tell the rich young ruler to do?',
 '["Build a tower","Sell all and follow Me","Take up a sword","Memorize the Law"]'::jsonb,1,'Matthew 19:21',
 'Jesus said, “If you want to be perfect, go, sell what you have… and come, follow Me” (Matthew 19:21).'),
('new_testament','medium','Whose mother-in-law did Jesus heal of a fever?',
 '["Andrew''s","Peter''s","James''","John''s"]'::jsonb,1,'Matthew 8:14-15',
 'Jesus healed Peter''s mother-in-law of a fever, and she rose and served Him (Matthew 8:14-15).'),
('new_testament','medium','Which feast was Jesus crucified during?',
 '["Tabernacles","Pentecost","Passover","Purim"]'::jsonb,2,'Matthew 26:2',
 'Jesus was handed over to be crucified at Passover, fulfilling the picture of the Passover Lamb (Matthew 26:2; 1 Corinthians 5:7).'),
('new_testament','medium','What sign accompanied Jesus'' death at the temple?',
 '["A pillar of fire","The veil was torn from top to bottom","The altar collapsed","A new lampstand appeared"]'::jsonb,1,'Matthew 27:51',
 'At the moment Jesus died, the temple veil was torn in two from top to bottom, opening the way to God (Matthew 27:51).'),
('new_testament','medium','At what hour did Jesus die on the cross?',
 '["The third hour","The sixth hour","The ninth hour","The eleventh hour"]'::jsonb,2,'Matthew 27:46',
 'About the ninth hour (3 PM), Jesus cried out, “My God, My God, why have You forsaken Me?” and yielded up His spirit (Matthew 27:46-50).'),
('new_testament','medium','Which two disciples met the risen Jesus on the road?',
 '["To Bethany","To Damascus","To Emmaus","To Joppa"]'::jsonb,2,'Luke 24:13-32',
 'On the road to Emmaus, Jesus walked with two disciples and opened the Scriptures concerning Himself (Luke 24:13-32).'),
('new_testament','medium','Who was the Roman governor who sentenced Jesus?',
 '["Felix","Festus","Pontius Pilate","Herod"]'::jsonb,2,'Matthew 27:24-26',
 'Pontius Pilate, the Roman prefect of Judea, washed his hands and delivered Jesus to be crucified (Matthew 27:24-26).'),
('new_testament','medium','Who was the high priest who interrogated Jesus?',
 '["Annas","Caiaphas","Zadok","Eli"]'::jsonb,1,'Matthew 26:57',
 'They led Jesus to Caiaphas the high priest, where the scribes and elders were assembled (Matthew 26:57).'),
('new_testament','medium','Who replaced Judas Iscariot among the apostles?',
 '["Barnabas","Stephen","Matthias","Silas"]'::jsonb,2,'Acts 1:26',
 'The eleven cast lots, and the lot fell on Matthias; he was numbered with the apostles (Acts 1:26).'),
('new_testament','medium','Which church was the first to be called "Christians"?',
 '["Jerusalem","Antioch","Rome","Corinth"]'::jsonb,1,'Acts 11:26',
 'The disciples were first called Christians in Antioch, where Barnabas and Saul taught for a year (Acts 11:26).'),
('new_testament','medium','Where was Paul shipwrecked on his way to Rome?',
 '["Cyprus","Malta","Crete","Rhodes"]'::jsonb,1,'Acts 28:1',
 'After the storm, they learned the island was called Melita (Malta), where Paul ministered (Acts 28:1-10).'),
('new_testament','medium','Which letter is known as the love chapter?',
 '["Romans 8","1 Corinthians 13","Ephesians 5","1 John 4"]'::jsonb,1,'1 Corinthians 13',
 'Paul devotes 1 Corinthians 13 to the supremacy of love — patient, kind, never failing.'),
('new_testament','medium','Which letter teaches putting on the armor of God?',
 '["Romans","Philippians","Ephesians","Colossians"]'::jsonb,2,'Ephesians 6:11',
 'Paul commands believers to put on the whole armor of God to stand against the schemes of the devil (Ephesians 6:11-18).'),
('new_testament','medium','Which book says "faith without works is dead"?',
 '["Romans","Galatians","James","Hebrews"]'::jsonb,2,'James 2:17',
 'James writes, “Faith by itself, if it does not have works, is dead” (James 2:17).'),
('new_testament','medium','To whom did Paul write a letter from prison about a runaway slave?',
 '["Philemon","Titus","Timothy","Philippians"]'::jsonb,0,'Philemon 1:10',
 'Paul wrote Philemon urging him to receive back Onesimus, now a brother in Christ (Philemon 1:10-17).'),
('new_testament','medium','Who said, "Silver and gold I do not have, but what I have I give"?',
 '["John","Peter","Stephen","Paul"]'::jsonb,1,'Acts 3:6',
 'Peter healed a lame man at the temple gate by the name of Jesus Christ of Nazareth (Acts 3:6).'),
('new_testament','medium','What was the name of the lake where many of Jesus'' miracles occurred?',
 '["Jordan","Galilee","Tiberias only","Hula"]'::jsonb,1,'Matthew 4:18',
 'The Sea of Galilee — also called Tiberias and Gennesaret — was where Jesus called fishermen and stilled storms (Matthew 4:18).'),
('new_testament','medium','How long did Jesus fast in the wilderness before being tempted?',
 '["Three days","Seven days","Forty days","Eighty days"]'::jsonb,2,'Matthew 4:2',
 'Jesus fasted forty days and forty nights, then was afterward hungry (Matthew 4:2).'),
('new_testament','medium','How many temptations of Jesus does Matthew record?',
 '["One","Two","Three","Four"]'::jsonb,2,'Matthew 4:3-10',
 'Matthew records three temptations: bread from stones, leaping from the temple, and worshiping Satan for the kingdoms (Matthew 4:3-10).'),
('new_testament','medium','Who was the runaway slave Paul sent back to his master?',
 '["Tychicus","Onesimus","Epaphras","Trophimus"]'::jsonb,1,'Philemon 1:10',
 'Onesimus, formerly unprofitable, had become useful to Paul and was sent back to Philemon as a beloved brother (Philemon 1:10-16).'),
('new_testament','medium','Which apostle was called Cephas?',
 '["John","Peter","Andrew","James"]'::jsonb,1,'John 1:42',
 'Jesus said, “You shall be called Cephas” (which is translated, A Stone / Peter) (John 1:42).'),

('new_testament','hard','In how many languages was the inscription on Jesus'' cross?',
 '["One","Two","Three","Four"]'::jsonb,2,'John 19:20',
 'The inscription was written in Hebrew, Greek, and Latin so all could read it (John 19:20).'),
('new_testament','hard','Which two apostles did Jesus call "Sons of Thunder"?',
 '["Peter and Andrew","James and John","Philip and Bartholomew","Simon and Thaddaeus"]'::jsonb,1,'Mark 3:17',
 'Jesus surnamed James and John, sons of Zebedee, Boanerges — that is, “Sons of Thunder” (Mark 3:17).'),
('new_testament','hard','Which apostle was a tax collector named Levi?',
 '["Matthew","Thomas","James the Less","Bartholomew"]'::jsonb,0,'Matthew 9:9; Mark 2:14',
 'Matthew (also called Levi) was sitting at the tax office when Jesus called him to follow (Matthew 9:9; Mark 2:14).'),
('new_testament','hard','What does "Maranatha" mean?',
 '["Holy is the Lord","Our Lord, come","Praise the Lord","Christ is risen"]'::jsonb,1,'1 Corinthians 16:22',
 'Maranatha is an Aramaic expression meaning “Our Lord, come!” — a longing for Christ''s return (1 Corinthians 16:22).'),
('new_testament','hard','How many books did Paul write to Timothy?',
 '["One","Two","Three","Four"]'::jsonb,1,'1 & 2 Timothy',
 'Paul wrote two pastoral letters to Timothy, his young son in the faith (1 & 2 Timothy).'),
('new_testament','hard','Which book mentions "a great cloud of witnesses"?',
 '["Romans","Hebrews","1 Peter","Revelation"]'::jsonb,1,'Hebrews 12:1',
 'Hebrews 12:1 calls believers to run with endurance, surrounded by so great a cloud of witnesses.'),
('new_testament','hard','Who was Paul''s Greek companion who was not circumcised?',
 '["Timothy","Titus","Luke","Silas"]'::jsonb,1,'Galatians 2:3',
 'Paul refused to have Titus circumcised, defending the truth of the gospel from Judaizers (Galatians 2:3-5).'),
('new_testament','hard','Who was the seller of purple Paul converted at Philippi?',
 '["Phoebe","Lydia","Priscilla","Damaris"]'::jsonb,1,'Acts 16:14',
 'Lydia, a seller of purple from Thyatira, worshiped God and was baptized with her household (Acts 16:14-15).'),
('new_testament','hard','Which Ephesian silversmith stirred a riot against Paul?',
 '["Demetrius","Alexander","Erastus","Tertullus"]'::jsonb,0,'Acts 19:24-28',
 'Demetrius the silversmith feared loss of trade in silver shrines of Diana and incited a city-wide riot (Acts 19:24-28).'),
('new_testament','hard','Before which Roman governor did Paul defend himself in Caesarea?',
 '["Pilate","Felix","Sergius Paulus","Gallio"]'::jsonb,1,'Acts 24:24',
 'Paul reasoned of righteousness, self-control, and judgment to come before Felix, who became afraid (Acts 24:24-25).'),
('new_testament','hard','Which king said to Paul, "You almost persuade me to become a Christian"?',
 '["Herod Antipas","Agrippa","Festus","Caesar"]'::jsonb,1,'Acts 26:28',
 'King Agrippa said, “You almost persuade me to become a Christian,” after Paul''s defense (Acts 26:28).'),
('new_testament','hard','Where was Saul going when Jesus appeared to him?',
 '["Jerusalem","Damascus","Antioch","Tarsus"]'::jsonb,1,'Acts 9:3',
 'As Saul journeyed to Damascus to persecute believers, a light from heaven shone around him (Acts 9:3-5).'),
('new_testament','hard','Who was Paul''s young protégé from Lystra?',
 '["Titus","Timothy","Luke","Trophimus"]'::jsonb,1,'Acts 16:1-3',
 'Paul met Timothy at Lystra — son of a believing Jewish mother and a Greek father — and took him as a companion (Acts 16:1-3).'),
('new_testament','hard','Which deacon was "full of faith and the Holy Spirit"?',
 '["Philip","Stephen","Nicanor","Parmenas"]'::jsonb,1,'Acts 6:5',
 'Stephen was named first among the seven, “a man full of faith and the Holy Spirit” (Acts 6:5).'),
('new_testament','hard','Which Gospel begins "In the beginning was the Word"?',
 '["Matthew","Mark","Luke","John"]'::jsonb,3,'John 1:1',
 'John opens his Gospel: “In the beginning was the Word, and the Word was with God, and the Word was God” (John 1:1).'),
('new_testament','hard','Which Gospel begins with a genealogy from Abraham?',
 '["Matthew","Mark","Luke","John"]'::jsonb,0,'Matthew 1:1',
 'Matthew traces Jesus'' lineage from Abraham through David, establishing Him as Messiah and King (Matthew 1:1-17).'),
('new_testament','hard','Which Gospel begins with John the Baptist''s ministry?',
 '["Matthew","Mark","Luke","John"]'::jsonb,1,'Mark 1:1-4',
 'Mark opens immediately with John the Baptist preparing the way of the Lord (Mark 1:1-4).'),
('new_testament','hard','Which apostle is called "the beloved disciple"?',
 '["Peter","James","John","Andrew"]'::jsonb,2,'John 13:23; 21:20',
 'John refers to himself as “the disciple whom Jesus loved,” identifying himself indirectly (John 13:23; 21:20).'),
('new_testament','hard','Who was Jesus'' prophetess witness at the temple presentation?',
 '["Hannah","Anna","Elizabeth","Mary of Bethany"]'::jsonb,1,'Luke 2:36-38',
 'Anna, an elderly widow and prophetess, gave thanks and spoke of Jesus to all who looked for redemption (Luke 2:36-38).'),
('new_testament','hard','Who was the elderly man who blessed baby Jesus in the temple?',
 '["Simeon","Zacharias","Joseph","Cleopas"]'::jsonb,0,'Luke 2:25-32',
 'Simeon, righteous and devout, took the Child in his arms and sang the Nunc Dimittis (Luke 2:25-32).'),
('new_testament','hard','Which centurion at the cross said, "Truly this was the Son of God"?',
 '["Cornelius","Julius","An unnamed centurion","Claudius Lysias"]'::jsonb,2,'Matthew 27:54',
 'An unnamed centurion and those guarding Jesus said, “Truly this was the Son of God!” after the earthquake (Matthew 27:54).'),
('new_testament','hard','Which criminal was released instead of Jesus?',
 '["Barabbas","Saul","Demetrius","Eutychus"]'::jsonb,0,'Matthew 27:16-26',
 'Pilate released Barabbas, a notorious prisoner, in response to the crowd''s demand at Passover (Matthew 27:16-26).'),
('new_testament','hard','Who beheaded John the Baptist?',
 '["Pilate","Herod Antipas","Herod the Great","Felix"]'::jsonb,1,'Mark 6:14-28',
 'Herod Antipas ordered John''s beheading after Herodias''s daughter danced at his birthday banquet (Mark 6:14-28).'),
('new_testament','hard','What does "Cephas" mean?',
 '["Beloved","Rock","Faithful","Sent one"]'::jsonb,1,'John 1:42',
 'Jesus gave Simon the Aramaic name Cephas, translated Peter — meaning “stone” or “rock” (John 1:42).'),
('new_testament','hard','How many apostles wrote epistles preserved in the New Testament?',
 '["Three","Four","Five","Six"]'::jsonb,1,'NT canon',
 'Four apostles wrote NT epistles: Paul, Peter, John, and James (plus Jude, the brother of James).'),
('new_testament','hard','Where did Pentecost happen?',
 '["Bethlehem","Jerusalem","Antioch","Caesarea"]'::jsonb,1,'Acts 2:1-5',
 'The Spirit was poured out on the disciples gathered in Jerusalem on the day of Pentecost (Acts 2:1-5).'),
('new_testament','hard','What did Peter see in his vision before going to Cornelius?',
 '["A burning lampstand","A sheet of unclean animals","A flying scroll","A white horse"]'::jsonb,1,'Acts 10:9-16',
 'Peter saw a great sheet descending with all kinds of animals, and heard, “What God has cleansed do not call common” (Acts 10:9-16).'),
('new_testament','hard','What did Jesus do before raising Lazarus?',
 '["Anointed the tomb","Wept","Cast lots","Read from Isaiah"]'::jsonb,1,'John 11:35',
 'Seeing Mary and the mourners weeping, Jesus groaned in His spirit and wept (John 11:33-35).'),

('character','easy','Who was the wife of Adam?',
 '["Sarah","Eve","Rebekah","Rachel"]'::jsonb,1,'Genesis 3:20',
 'Adam called his wife''s name Eve, because she was the mother of all living (Genesis 3:20).'),
('character','easy','Who was Adam''s third son after Cain and Abel?',
 '["Enoch","Seth","Lamech","Methuselah"]'::jsonb,1,'Genesis 4:25',
 'Eve bore another son and named him Seth, “for God has appointed another seed for me instead of Abel” (Genesis 4:25).'),
('character','easy','Who tricked Isaac into giving him the blessing?',
 '["Esau","Jacob","Joseph","Reuben"]'::jsonb,1,'Genesis 27',
 'Jacob, with Rebekah''s help, deceived the blind Isaac and received the firstborn''s blessing meant for Esau (Genesis 27:18-29).'),
('character','easy','Who was Jacob''s twin brother?',
 '["Esau","Laban","Reuben","Joseph"]'::jsonb,0,'Genesis 25:25-26',
 'Esau was the firstborn of the twins, red and hairy; Jacob came out holding his heel (Genesis 25:25-26).'),
('character','easy','Who was Joseph''s father?',
 '["Isaac","Abraham","Jacob","Esau"]'::jsonb,2,'Genesis 30:22-24',
 'Joseph was the son of Jacob and Rachel, born after years of barrenness (Genesis 30:22-24).'),
('character','easy','Who was Joseph''s youngest brother?',
 '["Benjamin","Judah","Simeon","Levi"]'::jsonb,0,'Genesis 35:18',
 'Rachel died giving birth to Benjamin, Joseph''s only full brother and Jacob''s youngest son (Genesis 35:18).'),
('character','easy','Who interpreted Pharaoh''s dreams?',
 '["The chief baker","Joseph","Moses","Aaron"]'::jsonb,1,'Genesis 41:25-32',
 'Joseph interpreted Pharaoh''s dreams of cows and grain, foretelling seven years of plenty and famine (Genesis 41:25-32).'),
('character','easy','Who hid baby Moses in a basket?',
 '["His sister","His mother","Pharaoh''s daughter","Pharaoh''s wife"]'::jsonb,1,'Exodus 2:3',
 'Moses'' mother Jochebed hid him three months, then placed him in a basket among the reeds of the Nile (Exodus 2:3).'),
('character','easy','Who found baby Moses in the river?',
 '["Pharaoh''s daughter","Pharaoh","Miriam","Zipporah"]'::jsonb,0,'Exodus 2:5',
 'Pharaoh''s daughter went to bathe at the river and discovered the basket with the crying baby (Exodus 2:5-6).'),
('character','easy','Who was Moses'' wife?',
 '["Miriam","Zipporah","Rebekah","Bilhah"]'::jsonb,1,'Exodus 2:21',
 'Moses dwelt with Jethro in Midian and married his daughter Zipporah (Exodus 2:21).'),
('character','easy','Who was Moses'' sister?',
 '["Miriam","Sarah","Hannah","Anna"]'::jsonb,0,'Exodus 15:20',
 'Miriam, the prophetess, was Moses'' older sister and led the women in praise after the Red Sea crossing (Exodus 15:20-21).'),
('character','easy','Who was the female judge of Israel?',
 '["Deborah","Esther","Ruth","Huldah"]'::jsonb,0,'Judges 4:4',
 'Deborah was both judge and prophetess in Israel during the oppression by Jabin, king of Canaan (Judges 4:4).'),
('character','easy','Who was Naomi''s loyal daughter-in-law?',
 '["Orpah","Ruth","Hannah","Abigail"]'::jsonb,1,'Ruth 1:16',
 'Ruth declared to Naomi, “Wherever you go, I will go; your people shall be my people, and your God my God” (Ruth 1:16).'),
('character','easy','Who was David''s best friend?',
 '["Jonathan","Samuel","Nathan","Joab"]'::jsonb,0,'1 Samuel 18:1',
 'The soul of Jonathan was knit to the soul of David, and Jonathan loved him as his own soul (1 Samuel 18:1).'),
('character','easy','Who was Solomon''s father?',
 '["Saul","David","Samuel","Jonathan"]'::jsonb,1,'1 Kings 1:11',
 'Solomon, son of David and Bathsheba, succeeded his father as king (1 Kings 1:11; 2:12).'),
('character','easy','Who is called "a man after God''s own heart"?',
 '["Moses","Abraham","David","Daniel"]'::jsonb,2,'1 Samuel 13:14; Acts 13:22',
 'God testified that David was “a man after My own heart, who will do all My will” (Acts 13:22; 1 Samuel 13:14).'),
('character','easy','Who was Esther''s cousin and guardian?',
 '["Haman","Mordecai","Ahasuerus","Vashti"]'::jsonb,1,'Esther 2:7',
 'Mordecai raised his cousin Esther as his own daughter when her parents died (Esther 2:7).'),
('character','easy','Who plotted to destroy the Jews in Esther''s day?',
 '["Mordecai","Haman","Ahasuerus","Cyrus"]'::jsonb,1,'Esther 3:8-15',
 'Haman the Agagite, the king''s second-in-command, plotted to destroy all the Jews in the empire (Esther 3:8-15).'),
('character','easy','Who denied Jesus three times?',
 '["John","Peter","Judas","Andrew"]'::jsonb,1,'Matthew 26:69-75',
 'Peter denied knowing Jesus three times in the high priest''s courtyard before the rooster crowed (Matthew 26:69-75).'),
('character','easy','Who betrayed Jesus with a kiss?',
 '["Peter","Thomas","Judas Iscariot","Simon"]'::jsonb,2,'Matthew 26:48-49',
 'Judas Iscariot gave a sign saying, “Whomever I kiss, He is the One,” and betrayed Jesus to the guards (Matthew 26:48-49).'),
('character','easy','Who was Jesus'' mother?',
 '["Elizabeth","Mary","Martha","Salome"]'::jsonb,1,'Matthew 1:18',
 'Mary, betrothed to Joseph, conceived Jesus by the Holy Spirit (Matthew 1:18; Luke 1:35).'),
('character','easy','Who was Jesus'' friend raised from the dead?',
 '["Jairus'' son","Lazarus","The widow''s son","Tabitha"]'::jsonb,1,'John 11',
 'Jesus called Lazarus from the tomb after he had been dead four days, glorifying God before the watching crowd (John 11:43-44).'),
('character','easy','Who was the busy sister of Mary, distracted with serving?',
 '["Martha","Joanna","Salome","Anna"]'::jsonb,0,'Luke 10:40',
 'Martha was distracted with much serving while her sister Mary sat at Jesus'' feet to hear His word (Luke 10:39-40).'),
('character','easy','Who was the doubting disciple?',
 '["Andrew","Thomas","Philip","Matthew"]'::jsonb,1,'John 20:25-28',
 'Thomas would not believe until he had seen the print of the nails and felt the Lord''s side (John 20:25-28).'),
('character','easy','Who is called "the rock"?',
 '["Andrew","Peter","John","James"]'::jsonb,1,'Matthew 16:18',
 'Jesus said, “You are Peter, and on this rock I will build My church” (Matthew 16:18).'),
('character','easy','Who was the apostle to the Gentiles?',
 '["Peter","Paul","Barnabas","James"]'::jsonb,1,'Romans 11:13',
 'Paul wrote, “Inasmuch as I am an apostle to the Gentiles, I magnify my ministry” (Romans 11:13).'),
('character','easy','Who was the prophet Elijah''s servant and successor?',
 '["Gehazi","Elisha","Obadiah","Micaiah"]'::jsonb,1,'2 Kings 2:9-15',
 'Elisha served Elijah and received a double portion of his spirit when Elijah was taken up (2 Kings 2:9-15).'),
('character','easy','Who built the ark?',
 '["Noah","Abraham","Moses","David"]'::jsonb,0,'Genesis 6:14-22',
 'Noah obeyed God and built the ark of gopherwood exactly as God commanded (Genesis 6:14-22).'),
('character','easy','Who married Rebekah?',
 '["Abraham","Isaac","Jacob","Esau"]'::jsonb,1,'Genesis 24:67',
 'Isaac brought Rebekah into his mother Sarah''s tent, took her as his wife, and loved her (Genesis 24:67).'),
('character','easy','Who hid the Israelite spies in Jericho?',
 '["Deborah","Rahab","Ruth","Jael"]'::jsonb,1,'Joshua 2:1-6',
 'Rahab the harlot welcomed the spies and hid them under stalks of flax on her roof (Joshua 2:1-6).'),

('character','medium','Who walked with God and was taken without dying?',
 '["Noah","Enoch","Elijah","Methuselah"]'::jsonb,1,'Genesis 5:24',
 'Enoch walked with God; and he was not, for God took him (Genesis 5:24).'),
('character','medium','Who were Noah''s three sons?',
 '["Cain, Abel, Seth","Shem, Ham, Japheth","Reuben, Simeon, Levi","Eber, Peleg, Joktan"]'::jsonb,1,'Genesis 5:32',
 'Noah''s three sons — Shem, Ham, and Japheth — were the fathers of every nation after the flood (Genesis 5:32; 10).'),
('character','medium','Who was Abraham''s wife?',
 '["Sarah","Rebekah","Hagar","Rachel"]'::jsonb,0,'Genesis 17:15',
 'Sarah was Abraham''s wife and the mother of Isaac, the child of promise (Genesis 17:15-19; 21:1-3).'),
('character','medium','Who was Sarah''s Egyptian handmaid?',
 '["Rebekah","Hagar","Bilhah","Zilpah"]'::jsonb,1,'Genesis 16:1',
 'Hagar was Sarah''s Egyptian handmaid; through her Ishmael was born to Abraham (Genesis 16:1-15).'),
('character','medium','Who was Rebekah''s brother who hosted Jacob?',
 '["Bethuel","Laban","Esau","Nahor"]'::jsonb,1,'Genesis 29:13-14',
 'Laban welcomed his nephew Jacob and later gave both his daughters to him as wives (Genesis 29:13-30).'),
('character','medium','Who was Jacob''s first wife by Laban''s deception?',
 '["Rachel","Leah","Bilhah","Zilpah"]'::jsonb,1,'Genesis 29:23',
 'In the morning Jacob discovered Laban had given him Leah instead of Rachel (Genesis 29:23-25).'),
('character','medium','Who was Jacob''s beloved wife and mother of Joseph?',
 '["Leah","Rachel","Bilhah","Zilpah"]'::jsonb,1,'Genesis 29:30; 30:22-24',
 'Jacob loved Rachel more than Leah; she bore Joseph and later Benjamin (Genesis 29:30; 30:22-24).'),
('character','medium','Who was the Egyptian official who bought Joseph as a slave?',
 '["Potiphar","Pharaoh","The chief baker","Asenath"]'::jsonb,0,'Genesis 39:1',
 'Potiphar, captain of Pharaoh''s guard, bought Joseph from the Ishmaelites (Genesis 39:1).'),
('character','medium','Who was Bathsheba''s first husband?',
 '["Joab","Uriah the Hittite","Nathan","Abner"]'::jsonb,1,'2 Samuel 11:3',
 'Bathsheba was the wife of Uriah the Hittite — one of David''s mighty men, killed by David''s scheme (2 Samuel 11:3-17).'),
('character','medium','Who was David''s nephew and military commander?',
 '["Abner","Joab","Benaiah","Adoniram"]'::jsonb,1,'2 Samuel 8:16',
 'Joab the son of Zeruiah was David''s commander of the army and his nephew (2 Samuel 8:16; 1 Chronicles 2:16).'),
('character','medium','Who was Solomon''s heir whose folly split Israel?',
 '["Jeroboam","Rehoboam","Abijah","Jehoram"]'::jsonb,1,'1 Kings 12',
 'Rehoboam rejected the elders'' counsel and threatened harsher labor; the northern tribes seceded (1 Kings 12:6-19).'),
('character','medium','Who was the wicked queen who killed prophets of God?',
 '["Athaliah","Jezebel","Vashti","Maacah"]'::jsonb,1,'1 Kings 18:4',
 'Jezebel, Ahab''s wife, massacred the prophets of the Lord and persecuted Elijah (1 Kings 18:4; 19:2).'),
('character','medium','Who succeeded Aaron as high priest?',
 '["Eli","Eleazar","Phinehas","Abiathar"]'::jsonb,1,'Numbers 20:28',
 'Moses took the priestly garments and put them on Eleazar, Aaron''s son, on Mount Hor (Numbers 20:28).'),
('character','medium','Who was the prophet who anointed Solomon king?',
 '["Nathan and Zadok","Samuel","Elijah","Gad"]'::jsonb,0,'1 Kings 1:38-39',
 'Nathan the prophet and Zadok the priest anointed Solomon king at Gihon (1 Kings 1:38-39).'),
('character','medium','Who was the prophet who lay with his face down and parted the Jordan with his mantle?',
 '["Elisha","Elijah","Isaiah","Jeremiah"]'::jsonb,1,'2 Kings 2:8',
 'Elijah took his mantle, struck the waters, and they parted so he and Elisha crossed on dry ground (2 Kings 2:8).'),
('character','medium','Who was the prophet whose servant''s eyes were opened to see chariots of fire?',
 '["Elijah","Elisha","Daniel","Jonah"]'::jsonb,1,'2 Kings 6:17',
 'Elisha prayed, “Lord, open his eyes,” and Gehazi saw the mountain full of horses and chariots of fire (2 Kings 6:17).'),
('character','medium','Who was the queen of Judah who tried to destroy the royal seed?',
 '["Jezebel","Athaliah","Vashti","Esther"]'::jsonb,1,'2 Kings 11:1',
 'Athaliah, Ahaziah''s mother, killed all the royal heirs except baby Joash, who was hidden (2 Kings 11:1-3).'),
('character','medium','Who was the elderly prophet Mary visited while pregnant?',
 '["Anna","Elizabeth","Salome","Joanna"]'::jsonb,1,'Luke 1:39-45',
 'Mary visited Elizabeth, mother of John the Baptist, who blessed her and the fruit of her womb (Luke 1:39-45).'),
('character','medium','Whose mother sang the Magnificat?',
 '["John the Baptist","Jesus","Samuel","Isaac"]'::jsonb,1,'Luke 1:46-55',
 'Mary, Jesus'' mother, sang the Magnificat: “My soul magnifies the Lord” (Luke 1:46-55).'),
('character','medium','Who was Elizabeth''s husband?',
 '["Joseph","Zacharias","Simeon","Eli"]'::jsonb,1,'Luke 1:5',
 'Zacharias the priest and his wife Elizabeth were both righteous before God (Luke 1:5-6).'),
('character','medium','Who washed his hands of responsibility for Jesus'' death?',
 '["Caiaphas","Pilate","Annas","Herod"]'::jsonb,1,'Matthew 27:24',
 'Pilate washed his hands before the crowd and declared, “I am innocent of the blood of this just Person” (Matthew 27:24).'),
('character','medium','Who was the criminal released instead of Jesus?',
 '["Bar-Jesus","Barabbas","Stephen","Saul"]'::jsonb,1,'Matthew 27:16-26',
 'Pilate released Barabbas, a notorious prisoner, at the crowd''s demand (Matthew 27:16-26).'),
('character','medium','Whose daughter danced before Herod for John the Baptist''s head?',
 '["Mary Magdalene''s","Herodias''","Pilate''s wife''s","Drusilla''s"]'::jsonb,1,'Mark 6:22',
 'The daughter of Herodias danced before Herod and asked for John the Baptist''s head on a platter (Mark 6:22-25).'),
('character','medium','Who was the Pharisee who came to Jesus by night?',
 '["Joseph of Arimathea","Nicodemus","Gamaliel","Saul"]'::jsonb,1,'John 3:1-2',
 'Nicodemus, a ruler of the Jews, came to Jesus by night and heard, “You must be born again” (John 3:1-7).'),
('character','medium','Who became the disciple Jesus called from a sycamore tree?',
 '["Levi","Zacchaeus","Nathanael","Lazarus"]'::jsonb,1,'Luke 19:1-10',
 'Zacchaeus the chief tax collector climbed a sycamore to see Jesus, who then dined at his house (Luke 19:1-10).'),
('character','medium','Who was Paul''s first traveling companion?',
 '["Silas","Barnabas","Timothy","Mark"]'::jsonb,1,'Acts 13:2',
 'The Spirit set apart Barnabas and Saul to be sent out on the first missionary journey (Acts 13:2-4).'),
('character','medium','Who was Paul''s second-journey companion after splitting from Barnabas?',
 '["Mark","Silas","Luke","Apollos"]'::jsonb,1,'Acts 15:40',
 'Paul chose Silas after a sharp disagreement with Barnabas over John Mark (Acts 15:36-40).'),
('character','medium','Who was the eloquent Jew of Alexandria who knew the Scriptures?',
 '["Apollos","Aquila","Demetrius","Sosthenes"]'::jsonb,0,'Acts 18:24',
 'Apollos was an eloquent man, mighty in the Scriptures, instructed in the way of the Lord (Acts 18:24-25).'),

('character','hard','Who was the father of Lot?',
 '["Nahor","Haran","Terah","Bethuel"]'::jsonb,1,'Genesis 11:27',
 'Haran was Lot''s father, and Haran was the brother of Abram (Genesis 11:27).'),
('character','hard','Who was Abraham''s father?',
 '["Nahor","Terah","Haran","Shem"]'::jsonb,1,'Genesis 11:27',
 'Terah begot Abram, Nahor, and Haran in Ur of the Chaldeans (Genesis 11:27).'),
('character','hard','Who was Tubal-Cain in Genesis?',
 '["A judge","An instructor of bronze and iron craftsmen","A king","A prophet"]'::jsonb,1,'Genesis 4:22',
 'Tubal-Cain was an instructor of every craftsman in bronze and iron (Genesis 4:22).'),
('character','hard','Who was Elisha''s greedy servant struck with leprosy?',
 '["Naaman","Gehazi","Hazael","Jehu"]'::jsonb,1,'2 Kings 5:20-27',
 'Gehazi ran after Naaman for silver and garments; Elisha pronounced leprosy on him and his descendants (2 Kings 5:20-27).'),
('character','hard','Who was Job''s first friend to speak?',
 '["Bildad","Zophar","Eliphaz","Elihu"]'::jsonb,2,'Job 4:1',
 'Eliphaz the Temanite was the first of Job''s three friends to answer him (Job 4:1).'),
('character','hard','Which disciple was a Zealot?',
 '["Simon Peter","Simon the Zealot","Andrew","Thaddaeus"]'::jsonb,1,'Matthew 10:4',
 'Simon the Zealot is named among the twelve apostles, distinguished from Simon Peter (Matthew 10:4).'),
('character','hard','Which apostle was the son of Alphaeus?',
 '["James (the lesser)","Andrew","Bartholomew","Thaddaeus"]'::jsonb,0,'Matthew 10:3',
 'James the son of Alphaeus, often called James the Less, was among the twelve (Matthew 10:3; Mark 15:40).'),
('character','hard','Which apostle was also named Lebbaeus Thaddaeus?',
 '["Judas (not Iscariot)","Simon","Bartholomew","Matthias"]'::jsonb,0,'Matthew 10:3',
 'Lebbaeus, surnamed Thaddaeus — also called Judas, not Iscariot — was one of the twelve (Matthew 10:3; John 14:22).'),
('character','hard','Who was Aquila''s wife and Paul''s co-worker?',
 '["Phoebe","Priscilla","Lydia","Damaris"]'::jsonb,1,'Acts 18:2',
 'Priscilla and her husband Aquila were tentmakers who taught Apollos more accurately (Acts 18:2, 26).'),
('character','hard','Which female deacon did Paul commend in Romans 16?',
 '["Phoebe","Lydia","Junia","Tryphena"]'::jsonb,0,'Romans 16:1',
 'Paul commends Phoebe, “a servant of the church in Cenchrea,” to the Roman believers (Romans 16:1-2).'),
('character','hard','Who was the only female apostle named by Paul?',
 '["Phoebe","Junia","Priscilla","Damaris"]'::jsonb,1,'Romans 16:7',
 'Paul greets Andronicus and Junia, “of note among the apostles,” fellow prisoners with him (Romans 16:7).'),
('character','hard','Who was Timothy''s mother?',
 '["Lois","Eunice","Phoebe","Drusilla"]'::jsonb,1,'2 Timothy 1:5',
 'Paul recalls Timothy''s genuine faith — first in his grandmother Lois and his mother Eunice (2 Timothy 1:5).'),
('character','hard','Who was Timothy''s grandmother?',
 '["Eunice","Lois","Drusilla","Joanna"]'::jsonb,1,'2 Timothy 1:5',
 'The faith first dwelt in Timothy''s grandmother Lois and then in his mother Eunice (2 Timothy 1:5).'),
('character','hard','Who was Demas?',
 '["A loyal disciple of Paul","A companion who forsook Paul, loving this present world","A high priest","A Roman official"]'::jsonb,1,'2 Timothy 4:10',
 'Paul records, “Demas has forsaken me, having loved this present world” (2 Timothy 4:10).'),
('character','hard','Who was Diotrephes?',
 '["A faithful elder","A self-loving leader who rejected John","A Roman governor","A teacher of false doctrine in Crete"]'::jsonb,1,'3 John 9-10',
 'Diotrephes loved preeminence and refused to receive the apostles, prating against them maliciously (3 John 9-10).'),
('character','hard','Who was Gaius in 3 John?',
 '["A false teacher","The beloved recipient of the letter","An elder of Ephesus","A Roman magistrate"]'::jsonb,1,'3 John 1',
 'The elder writes to “the beloved Gaius, whom I love in truth” for his faithful hospitality (3 John 1, 5-8).'),
('character','hard','Who anointed Jesus with costly perfume before His burial?',
 '["Mary Magdalene","Mary of Bethany","Martha","Joanna"]'::jsonb,1,'John 12:3',
 'Mary of Bethany anointed Jesus'' feet with very costly oil of spikenard and wiped them with her hair (John 12:3).'),
('character','hard','Who was Joseph of Arimathea?',
 '["A Pharisee","A rich disciple who gave Jesus his tomb","A scribe","A centurion"]'::jsonb,1,'Matthew 27:57-60',
 'Joseph of Arimathea, a rich man and disciple, asked Pilate for Jesus'' body and laid Him in his own new tomb (Matthew 27:57-60).'),
('character','hard','Who was the angel that announced Jesus'' birth to Mary?',
 '["Michael","Gabriel","Raphael","An unnamed angel"]'::jsonb,1,'Luke 1:26',
 'God sent the angel Gabriel to Nazareth to announce the birth of Jesus (Luke 1:26-33).'),
('character','hard','Who was Sapphira''s husband?',
 '["Ananias","Apollos","Aquila","Stephen"]'::jsonb,0,'Acts 5:1',
 'Ananias, with Sapphira his wife, sold a possession and lied to the Holy Spirit, falling dead (Acts 5:1-10).'),
('character','hard','Who was the magician Paul rebuked in Cyprus?',
 '["Simon","Elymas","Demetrius","Alexander"]'::jsonb,1,'Acts 13:8-11',
 'Elymas the sorcerer (also called Bar-Jesus) opposed Paul; Paul struck him blind for a season (Acts 13:8-11).'),
('character','hard','Who was the sorcerer in Samaria who tried to buy the Spirit?',
 '["Elymas","Simon","Demetrius","Bar-Jesus"]'::jsonb,1,'Acts 8:9-24',
 'Simon the sorcerer offered Peter money to receive power to give the Holy Spirit and was rebuked (Acts 8:18-24).'),
('character','hard','Who was the queen mother of King Asa removed for idolatry?',
 '["Athaliah","Maacah","Jezebel","Vashti"]'::jsonb,1,'1 Kings 15:13',
 'King Asa removed his grandmother Maacah from being queen mother because she made an idol of Asherah (1 Kings 15:13).'),
('character','hard','Who was Jephthah?',
 '["A Levite singer","A judge of Israel who made a rash vow","A king of Edom","A prophet"]'::jsonb,1,'Judges 11:30-39',
 'Jephthah, judge of Israel, vowed before battle and tragically had to fulfill that vow regarding his daughter (Judges 11:30-39).'),
('character','hard','Who was the prophetess consulted by King Josiah''s officials?',
 '["Anna","Huldah","Miriam","Deborah"]'::jsonb,1,'2 Kings 22:14',
 'Hilkiah and the king''s servants consulted Huldah the prophetess about the book of the Law found in the temple (2 Kings 22:14).'),
('character','hard','Who was Eutychus?',
 '["A deacon","A young man who fell from a window during Paul''s sermon","A Roman officer","A magician"]'::jsonb,1,'Acts 20:9-12',
 'Eutychus fell from the third loft while Paul preached late into the night; Paul raised him alive (Acts 20:9-12).'),
('character','hard','Who was Dorcas (Tabitha)?',
 '["A merchant in Thyatira","A disciple in Joppa raised by Peter","A prophetess at the temple","The wife of Cornelius"]'::jsonb,1,'Acts 9:36-41',
 'Tabitha (Dorcas), full of good works, died in Joppa and was raised by Peter''s prayer (Acts 9:36-41).'),
('character','hard','Who was Cornelius?',
 '["A Roman centurion at Caesarea who became the first Gentile convert","A king of Judea","A disciple in Jerusalem","A Greek philosopher"]'::jsonb,0,'Acts 10:1-2',
 'Cornelius, a centurion of the Italian Regiment, was a devout God-fearer whom Peter baptized (Acts 10:1-48).')

ON CONFLICT DO NOTHING;

