package com.grace.app.presentation.screens.leader

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.grace.app.data.datastore.UserPreferencesRepo
import com.grace.app.domain.model.ProgressSnapshot
import com.grace.app.domain.repository.LeaderRepository
import com.grace.app.domain.usecase.leader.GetMyMenteesUseCase
import com.grace.app.domain.usecase.meditation.GetAllMeditationsUseCase
import com.grace.app.domain.usecase.meditation.GetMeditationSubmissionsForUserUseCase
import com.grace.app.domain.util.Result
import com.grace.app.presentation.screens.progress.ExportPeriod
import com.grace.app.presentation.screens.progress.MyProgressUiState
import com.grace.app.presentation.screens.progress.ProgressReflectionItem
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * State for the leader-generated compliance report for a single member.
 * Wraps a [MyProgressUiState] verbatim so the existing buildProgressReport
 * helper can render it without modification — the only difference is the
 * `me` field holds the MEMBER's profile (not the leader's), and we carry
 * the leader's display name separately for the "Generated by" footer.
 */
data class MemberReportUiState(
    val isLoading: Boolean = true,
    /** Shape consumed by buildProgressReport — `me` is the member here. */
    val progressState: MyProgressUiState = MyProgressUiState(),
    /** Leader's display name for the audit attribution on the cover. */
    val generatedByLeaderName: String = "",
    /** Member's display name for the screen header. */
    val memberName: String = "",
    val error: String? = null
)

sealed interface MemberReportEvent {
    data class IncludeAllChanged(val on: Boolean) : MemberReportEvent
    data class IncludeAttendanceChanged(val on: Boolean) : MemberReportEvent
    data class IncludeMeditationChanged(val on: Boolean) : MemberReportEvent
    data class PeriodChanged(val period: ExportPeriod) : MemberReportEvent
}

@HiltViewModel
class MemberReportViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    private val leaderRepository: LeaderRepository,
    private val getMyMenteesUseCase: GetMyMenteesUseCase,
    private val getMeditationSubmissionsForUserUseCase: GetMeditationSubmissionsForUserUseCase,
    private val getAllMeditationsUseCase: GetAllMeditationsUseCase,
    private val prefs: UserPreferencesRepo
) : ViewModel() {

    private val memberId: String = savedStateHandle.get<String>("memberId").orEmpty()

    private val _uiState = MutableStateFlow(MemberReportUiState())
    val uiState: StateFlow<MemberReportUiState> = _uiState.asStateFlow()

    init { load() }

    private fun load() {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }

            // Member profile via the mentees query — already RLS-scoped to
            // this leader's cell. Senior leaders see everyone in that list.
            val mentees = (getMyMenteesUseCase() as? Result.Success)?.data.orEmpty()
            val member = mentees.firstOrNull { it.user.id == memberId }?.user

            // Attendance for the member — new repo method added in P.4.
            val attended = (leaderRepository.getMemberAttendance(memberId)
                as? Result.Success)?.data.orEmpty()

            // Meditation submissions for the member.
            val subs = (getMeditationSubmissionsForUserUseCase(memberId)
                as? Result.Success)?.data.orEmpty()
            val meds = runCatching {
                getAllMeditationsUseCase().first()
            }.getOrDefault(emptyList())
            val medsById = meds.associateBy { it.id }
            val reflections = subs.map { ProgressReflectionItem(it, medsById[it.meditationId]) }

            // Leader's own display name for the "Generated by" line.
            val leaderName = prefs.userName.first().orEmpty()

            // Progress snapshot — for proxy reports we leave the personal-
            // stats subsection empty (devo streak / community engagement
            // aren't meaningful for proxy-only members). The Compassion-
            // compliance sections (attendance + meditation) carry the load.
            val snapshot = ProgressSnapshot()

            _uiState.update {
                it.copy(
                    isLoading = false,
                    memberName = member?.name?.takeIf { n -> n.isNotBlank() }
                        ?: member?.email
                        ?: "Member",
                    generatedByLeaderName = leaderName,
                    progressState = MyProgressUiState(
                        isLoading = false,
                        snapshot = snapshot,
                        attendedEvents = attended,
                        reflections = reflections,
                        me = member,
                        // Default to Compassion-compliance flavor — attendance +
                        // meditation included, personal stats off. Same defaults
                        // as MyProgressUiState.
                    )
                )
            }
        }
    }

    fun onEvent(event: MemberReportEvent) {
        when (event) {
            is MemberReportEvent.IncludeAllChanged -> _uiState.update {
                it.copy(progressState = it.progressState.copy(includeAll = event.on))
            }
            is MemberReportEvent.IncludeAttendanceChanged -> _uiState.update {
                it.copy(
                    progressState = it.progressState.copy(includeAttendance = event.on)
                )
            }
            is MemberReportEvent.IncludeMeditationChanged -> _uiState.update {
                it.copy(
                    progressState = it.progressState.copy(includeMeditation = event.on)
                )
            }
            is MemberReportEvent.PeriodChanged -> _uiState.update {
                it.copy(progressState = it.progressState.copy(period = event.period))
            }
        }
    }
}
